// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: ranking.proto

package rankingservice

import (
	"context"

	"github.com/agoXQ/QuantLab/app/ranking/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AuthorRankingItem         = pb.AuthorRankingItem
	GetAuthorRankRequest      = pb.GetAuthorRankRequest
	GetAuthorRankResponse     = pb.GetAuthorRankResponse
	GetHistoryRankingRequest  = pb.GetHistoryRankingRequest
	GetHistoryRankingResponse = pb.GetHistoryRankingResponse
	GetRankingRequest         = pb.GetRankingRequest
	GetRankingResponse        = pb.GetRankingResponse
	GetStrategyRankRequest    = pb.GetStrategyRankRequest
	GetStrategyRankResponse   = pb.GetStrategyRankResponse
	HistoryPoint              = pb.HistoryPoint
	ListSnapshotsRequest      = pb.ListSnapshotsRequest
	ListSnapshotsResponse     = pb.ListSnapshotsResponse
	RankingItem               = pb.RankingItem
	RankingSnapshot           = pb.RankingSnapshot

	RankingService interface {
		GetRanking(ctx context.Context, in *GetRankingRequest, opts ...grpc.CallOption) (*GetRankingResponse, error)
		GetStrategyRank(ctx context.Context, in *GetStrategyRankRequest, opts ...grpc.CallOption) (*GetStrategyRankResponse, error)
		GetAuthorRank(ctx context.Context, in *GetAuthorRankRequest, opts ...grpc.CallOption) (*GetAuthorRankResponse, error)
		GetHistoryRanking(ctx context.Context, in *GetHistoryRankingRequest, opts ...grpc.CallOption) (*GetHistoryRankingResponse, error)
		ListSnapshots(ctx context.Context, in *ListSnapshotsRequest, opts ...grpc.CallOption) (*ListSnapshotsResponse, error)
	}

	defaultRankingService struct {
		cli zrpc.Client
	}
)

func NewRankingService(cli zrpc.Client) RankingService {
	return &defaultRankingService{
		cli: cli,
	}
}

func (m *defaultRankingService) GetRanking(ctx context.Context, in *GetRankingRequest, opts ...grpc.CallOption) (*GetRankingResponse, error) {
	client := pb.NewRankingServiceClient(m.cli.Conn())
	return client.GetRanking(ctx, in, opts...)
}

func (m *defaultRankingService) GetStrategyRank(ctx context.Context, in *GetStrategyRankRequest, opts ...grpc.CallOption) (*GetStrategyRankResponse, error) {
	client := pb.NewRankingServiceClient(m.cli.Conn())
	return client.GetStrategyRank(ctx, in, opts...)
}

func (m *defaultRankingService) GetAuthorRank(ctx context.Context, in *GetAuthorRankRequest, opts ...grpc.CallOption) (*GetAuthorRankResponse, error) {
	client := pb.NewRankingServiceClient(m.cli.Conn())
	return client.GetAuthorRank(ctx, in, opts...)
}

func (m *defaultRankingService) GetHistoryRanking(ctx context.Context, in *GetHistoryRankingRequest, opts ...grpc.CallOption) (*GetHistoryRankingResponse, error) {
	client := pb.NewRankingServiceClient(m.cli.Conn())
	return client.GetHistoryRanking(ctx, in, opts...)
}

func (m *defaultRankingService) ListSnapshots(ctx context.Context, in *ListSnapshotsRequest, opts ...grpc.CallOption) (*ListSnapshotsResponse, error) {
	client := pb.NewRankingServiceClient(m.cli.Conn())
	return client.ListSnapshots(ctx, in, opts...)
}
