// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: strategy.proto

package strategyservice

import (
	"context"

	"github.com/agoXQ/QuantLab/app/strategy/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ArchiveStrategyRequest   = pb.ArchiveStrategyRequest
	ArchiveStrategyResponse  = pb.ArchiveStrategyResponse
	CreateStrategyRequest    = pb.CreateStrategyRequest
	CreateStrategyResponse   = pb.CreateStrategyResponse
	CreateVersionRequest     = pb.CreateVersionRequest
	CreateVersionResponse    = pb.CreateVersionResponse
	DeleteStrategyRequest    = pb.DeleteStrategyRequest
	DeleteStrategyResponse   = pb.DeleteStrategyResponse
	ForkStrategyRequest      = pb.ForkStrategyRequest
	ForkStrategyResponse     = pb.ForkStrategyResponse
	GetStrategyRequest       = pb.GetStrategyRequest
	GetStrategyResponse      = pb.GetStrategyResponse
	GetVersionRequest        = pb.GetVersionRequest
	GetVersionResponse       = pb.GetVersionResponse
	ListStrategiesRequest    = pb.ListStrategiesRequest
	ListStrategiesResponse   = pb.ListStrategiesResponse
	ListVersionsRequest      = pb.ListVersionsRequest
	ListVersionsResponse     = pb.ListVersionsResponse
	PublishStrategyRequest   = pb.PublishStrategyRequest
	PublishStrategyResponse  = pb.PublishStrategyResponse
	SearchStrategiesRequest  = pb.SearchStrategiesRequest
	SearchStrategiesResponse = pb.SearchStrategiesResponse
	Strategy                 = pb.Strategy
	StrategyVersion          = pb.StrategyVersion
	UpdateStrategyRequest    = pb.UpdateStrategyRequest
	UpdateStrategyResponse   = pb.UpdateStrategyResponse

	StrategyService interface {
		CreateStrategy(ctx context.Context, in *CreateStrategyRequest, opts ...grpc.CallOption) (*CreateStrategyResponse, error)
		GetStrategy(ctx context.Context, in *GetStrategyRequest, opts ...grpc.CallOption) (*GetStrategyResponse, error)
		UpdateStrategy(ctx context.Context, in *UpdateStrategyRequest, opts ...grpc.CallOption) (*UpdateStrategyResponse, error)
		DeleteStrategy(ctx context.Context, in *DeleteStrategyRequest, opts ...grpc.CallOption) (*DeleteStrategyResponse, error)
		PublishStrategy(ctx context.Context, in *PublishStrategyRequest, opts ...grpc.CallOption) (*PublishStrategyResponse, error)
		ArchiveStrategy(ctx context.Context, in *ArchiveStrategyRequest, opts ...grpc.CallOption) (*ArchiveStrategyResponse, error)
		ForkStrategy(ctx context.Context, in *ForkStrategyRequest, opts ...grpc.CallOption) (*ForkStrategyResponse, error)
		CreateVersion(ctx context.Context, in *CreateVersionRequest, opts ...grpc.CallOption) (*CreateVersionResponse, error)
		ListVersions(ctx context.Context, in *ListVersionsRequest, opts ...grpc.CallOption) (*ListVersionsResponse, error)
		GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error)
		SearchStrategies(ctx context.Context, in *SearchStrategiesRequest, opts ...grpc.CallOption) (*SearchStrategiesResponse, error)
		ListStrategies(ctx context.Context, in *ListStrategiesRequest, opts ...grpc.CallOption) (*ListStrategiesResponse, error)
	}

	defaultStrategyService struct {
		cli zrpc.Client
	}
)

func NewStrategyService(cli zrpc.Client) StrategyService {
	return &defaultStrategyService{
		cli: cli,
	}
}

func (m *defaultStrategyService) CreateStrategy(ctx context.Context, in *CreateStrategyRequest, opts ...grpc.CallOption) (*CreateStrategyResponse, error) {
	client := pb.NewStrategyServiceClient(m.cli.Conn())
	return client.CreateStrategy(ctx, in, opts...)
}

func (m *defaultStrategyService) GetStrategy(ctx context.Context, in *GetStrategyRequest, opts ...grpc.CallOption) (*GetStrategyResponse, error) {
	client := pb.NewStrategyServiceClient(m.cli.Conn())
	return client.GetStrategy(ctx, in, opts...)
}

func (m *defaultStrategyService) UpdateStrategy(ctx context.Context, in *UpdateStrategyRequest, opts ...grpc.CallOption) (*UpdateStrategyResponse, error) {
	client := pb.NewStrategyServiceClient(m.cli.Conn())
	return client.UpdateStrategy(ctx, in, opts...)
}

func (m *defaultStrategyService) DeleteStrategy(ctx context.Context, in *DeleteStrategyRequest, opts ...grpc.CallOption) (*DeleteStrategyResponse, error) {
	client := pb.NewStrategyServiceClient(m.cli.Conn())
	return client.DeleteStrategy(ctx, in, opts...)
}

func (m *defaultStrategyService) PublishStrategy(ctx context.Context, in *PublishStrategyRequest, opts ...grpc.CallOption) (*PublishStrategyResponse, error) {
	client := pb.NewStrategyServiceClient(m.cli.Conn())
	return client.PublishStrategy(ctx, in, opts...)
}

func (m *defaultStrategyService) ArchiveStrategy(ctx context.Context, in *ArchiveStrategyRequest, opts ...grpc.CallOption) (*ArchiveStrategyResponse, error) {
	client := pb.NewStrategyServiceClient(m.cli.Conn())
	return client.ArchiveStrategy(ctx, in, opts...)
}

func (m *defaultStrategyService) ForkStrategy(ctx context.Context, in *ForkStrategyRequest, opts ...grpc.CallOption) (*ForkStrategyResponse, error) {
	client := pb.NewStrategyServiceClient(m.cli.Conn())
	return client.ForkStrategy(ctx, in, opts...)
}

func (m *defaultStrategyService) CreateVersion(ctx context.Context, in *CreateVersionRequest, opts ...grpc.CallOption) (*CreateVersionResponse, error) {
	client := pb.NewStrategyServiceClient(m.cli.Conn())
	return client.CreateVersion(ctx, in, opts...)
}

func (m *defaultStrategyService) ListVersions(ctx context.Context, in *ListVersionsRequest, opts ...grpc.CallOption) (*ListVersionsResponse, error) {
	client := pb.NewStrategyServiceClient(m.cli.Conn())
	return client.ListVersions(ctx, in, opts...)
}

func (m *defaultStrategyService) GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error) {
	client := pb.NewStrategyServiceClient(m.cli.Conn())
	return client.GetVersion(ctx, in, opts...)
}

func (m *defaultStrategyService) SearchStrategies(ctx context.Context, in *SearchStrategiesRequest, opts ...grpc.CallOption) (*SearchStrategiesResponse, error) {
	client := pb.NewStrategyServiceClient(m.cli.Conn())
	return client.SearchStrategies(ctx, in, opts...)
}

func (m *defaultStrategyService) ListStrategies(ctx context.Context, in *ListStrategiesRequest, opts ...grpc.CallOption) (*ListStrategiesResponse, error) {
	client := pb.NewStrategyServiceClient(m.cli.Conn())
	return client.ListStrategies(ctx, in, opts...)
}
