// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: strategy.proto

package server

import (
	"context"

	"github.com/agoXQ/QuantLab/app/strategy/internal/logic"
	"github.com/agoXQ/QuantLab/app/strategy/internal/svc"
	"github.com/agoXQ/QuantLab/app/strategy/pb"
)

type StrategyServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedStrategyServiceServer
}

func NewStrategyServiceServer(svcCtx *svc.ServiceContext) *StrategyServiceServer {
	return &StrategyServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *StrategyServiceServer) CreateStrategy(ctx context.Context, in *pb.CreateStrategyRequest) (*pb.CreateStrategyResponse, error) {
	l := logic.NewCreateStrategyLogic(ctx, s.svcCtx)
	return l.CreateStrategy(in)
}

func (s *StrategyServiceServer) GetStrategy(ctx context.Context, in *pb.GetStrategyRequest) (*pb.GetStrategyResponse, error) {
	l := logic.NewGetStrategyLogic(ctx, s.svcCtx)
	return l.GetStrategy(in)
}

func (s *StrategyServiceServer) UpdateStrategy(ctx context.Context, in *pb.UpdateStrategyRequest) (*pb.UpdateStrategyResponse, error) {
	l := logic.NewUpdateStrategyLogic(ctx, s.svcCtx)
	return l.UpdateStrategy(in)
}

func (s *StrategyServiceServer) DeleteStrategy(ctx context.Context, in *pb.DeleteStrategyRequest) (*pb.DeleteStrategyResponse, error) {
	l := logic.NewDeleteStrategyLogic(ctx, s.svcCtx)
	return l.DeleteStrategy(in)
}

func (s *StrategyServiceServer) PublishStrategy(ctx context.Context, in *pb.PublishStrategyRequest) (*pb.PublishStrategyResponse, error) {
	l := logic.NewPublishStrategyLogic(ctx, s.svcCtx)
	return l.PublishStrategy(in)
}

func (s *StrategyServiceServer) ArchiveStrategy(ctx context.Context, in *pb.ArchiveStrategyRequest) (*pb.ArchiveStrategyResponse, error) {
	l := logic.NewArchiveStrategyLogic(ctx, s.svcCtx)
	return l.ArchiveStrategy(in)
}

func (s *StrategyServiceServer) ForkStrategy(ctx context.Context, in *pb.ForkStrategyRequest) (*pb.ForkStrategyResponse, error) {
	l := logic.NewForkStrategyLogic(ctx, s.svcCtx)
	return l.ForkStrategy(in)
}

func (s *StrategyServiceServer) CreateVersion(ctx context.Context, in *pb.CreateVersionRequest) (*pb.CreateVersionResponse, error) {
	l := logic.NewCreateVersionLogic(ctx, s.svcCtx)
	return l.CreateVersion(in)
}

func (s *StrategyServiceServer) ListVersions(ctx context.Context, in *pb.ListVersionsRequest) (*pb.ListVersionsResponse, error) {
	l := logic.NewListVersionsLogic(ctx, s.svcCtx)
	return l.ListVersions(in)
}

func (s *StrategyServiceServer) GetVersion(ctx context.Context, in *pb.GetVersionRequest) (*pb.GetVersionResponse, error) {
	l := logic.NewGetVersionLogic(ctx, s.svcCtx)
	return l.GetVersion(in)
}

func (s *StrategyServiceServer) SearchStrategies(ctx context.Context, in *pb.SearchStrategiesRequest) (*pb.SearchStrategiesResponse, error) {
	l := logic.NewSearchStrategiesLogic(ctx, s.svcCtx)
	return l.SearchStrategies(in)
}

func (s *StrategyServiceServer) ListStrategies(ctx context.Context, in *pb.ListStrategiesRequest) (*pb.ListStrategiesResponse, error) {
	l := logic.NewListStrategiesLogic(ctx, s.svcCtx)
	return l.ListStrategies(in)
}
