// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: community.proto

package server

import (
	"context"

	"github.com/agoXQ/QuantLab/app/community/internal/logic"
	"github.com/agoXQ/QuantLab/app/community/internal/svc"
	"github.com/agoXQ/QuantLab/app/community/pb"
)

type CommunityServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedCommunityServiceServer
}

func NewCommunityServiceServer(svcCtx *svc.ServiceContext) *CommunityServiceServer {
	return &CommunityServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *CommunityServiceServer) CreateContent(ctx context.Context, in *pb.CreateContentRequest) (*pb.CreateContentResponse, error) {
	l := logic.NewCreateContentLogic(ctx, s.svcCtx)
	return l.CreateContent(in)
}

func (s *CommunityServiceServer) GetContent(ctx context.Context, in *pb.GetContentRequest) (*pb.GetContentResponse, error) {
	l := logic.NewGetContentLogic(ctx, s.svcCtx)
	return l.GetContent(in)
}

func (s *CommunityServiceServer) GetFeed(ctx context.Context, in *pb.GetFeedRequest) (*pb.GetFeedResponse, error) {
	l := logic.NewGetFeedLogic(ctx, s.svcCtx)
	return l.GetFeed(in)
}

func (s *CommunityServiceServer) LikeContent(ctx context.Context, in *pb.LikeContentRequest) (*pb.LikeContentResponse, error) {
	l := logic.NewLikeContentLogic(ctx, s.svcCtx)
	return l.LikeContent(in)
}

func (s *CommunityServiceServer) UnlikeContent(ctx context.Context, in *pb.UnlikeContentRequest) (*pb.UnlikeContentResponse, error) {
	l := logic.NewUnlikeContentLogic(ctx, s.svcCtx)
	return l.UnlikeContent(in)
}

func (s *CommunityServiceServer) FavoriteContent(ctx context.Context, in *pb.FavoriteContentRequest) (*pb.FavoriteContentResponse, error) {
	l := logic.NewFavoriteContentLogic(ctx, s.svcCtx)
	return l.FavoriteContent(in)
}

func (s *CommunityServiceServer) UnfavoriteContent(ctx context.Context, in *pb.UnfavoriteContentRequest) (*pb.UnfavoriteContentResponse, error) {
	l := logic.NewUnfavoriteContentLogic(ctx, s.svcCtx)
	return l.UnfavoriteContent(in)
}

func (s *CommunityServiceServer) CreateComment(ctx context.Context, in *pb.CreateCommentRequest) (*pb.CreateCommentResponse, error) {
	l := logic.NewCreateCommentLogic(ctx, s.svcCtx)
	return l.CreateComment(in)
}

func (s *CommunityServiceServer) ListComments(ctx context.Context, in *pb.ListCommentsRequest) (*pb.ListCommentsResponse, error) {
	l := logic.NewListCommentsLogic(ctx, s.svcCtx)
	return l.ListComments(in)
}

func (s *CommunityServiceServer) DeleteComment(ctx context.Context, in *pb.DeleteCommentRequest) (*pb.DeleteCommentResponse, error) {
	l := logic.NewDeleteCommentLogic(ctx, s.svcCtx)
	return l.DeleteComment(in)
}

func (s *CommunityServiceServer) GetProfile(ctx context.Context, in *pb.GetProfileRequest) (*pb.GetProfileResponse, error) {
	l := logic.NewGetProfileLogic(ctx, s.svcCtx)
	return l.GetProfile(in)
}

func (s *CommunityServiceServer) ListUserContents(ctx context.Context, in *pb.ListUserContentsRequest) (*pb.ListUserContentsResponse, error) {
	l := logic.NewListUserContentsLogic(ctx, s.svcCtx)
	return l.ListUserContents(in)
}
