// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: backtest.proto

package backtestservice

import (
	"context"

	"github.com/agoXQ/QuantLab/app/backtest/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BacktestConfig         = pb.BacktestConfig
	BacktestJob            = pb.BacktestJob
	CancelBacktestRequest  = pb.CancelBacktestRequest
	CancelBacktestResponse = pb.CancelBacktestResponse
	CreateBacktestRequest  = pb.CreateBacktestRequest
	CreateBacktestResponse = pb.CreateBacktestResponse
	GetBacktestRequest     = pb.GetBacktestRequest
	GetBacktestResponse    = pb.GetBacktestResponse
	GetPositionsRequest    = pb.GetPositionsRequest
	GetPositionsResponse   = pb.GetPositionsResponse
	GetReportRequest       = pb.GetReportRequest
	GetReportResponse      = pb.GetReportResponse
	GetTradesRequest       = pb.GetTradesRequest
	GetTradesResponse      = pb.GetTradesResponse
	ListBacktestsRequest   = pb.ListBacktestsRequest
	ListBacktestsResponse  = pb.ListBacktestsResponse
	PerformanceReport      = pb.PerformanceReport
	Position               = pb.Position
	Trade                  = pb.Trade

	BacktestService interface {
		CreateBacktest(ctx context.Context, in *CreateBacktestRequest, opts ...grpc.CallOption) (*CreateBacktestResponse, error)
		GetBacktest(ctx context.Context, in *GetBacktestRequest, opts ...grpc.CallOption) (*GetBacktestResponse, error)
		CancelBacktest(ctx context.Context, in *CancelBacktestRequest, opts ...grpc.CallOption) (*CancelBacktestResponse, error)
		GetReport(ctx context.Context, in *GetReportRequest, opts ...grpc.CallOption) (*GetReportResponse, error)
		GetTrades(ctx context.Context, in *GetTradesRequest, opts ...grpc.CallOption) (*GetTradesResponse, error)
		GetPositions(ctx context.Context, in *GetPositionsRequest, opts ...grpc.CallOption) (*GetPositionsResponse, error)
		ListBacktests(ctx context.Context, in *ListBacktestsRequest, opts ...grpc.CallOption) (*ListBacktestsResponse, error)
	}

	defaultBacktestService struct {
		cli zrpc.Client
	}
)

func NewBacktestService(cli zrpc.Client) BacktestService {
	return &defaultBacktestService{
		cli: cli,
	}
}

func (m *defaultBacktestService) CreateBacktest(ctx context.Context, in *CreateBacktestRequest, opts ...grpc.CallOption) (*CreateBacktestResponse, error) {
	client := pb.NewBacktestServiceClient(m.cli.Conn())
	return client.CreateBacktest(ctx, in, opts...)
}

func (m *defaultBacktestService) GetBacktest(ctx context.Context, in *GetBacktestRequest, opts ...grpc.CallOption) (*GetBacktestResponse, error) {
	client := pb.NewBacktestServiceClient(m.cli.Conn())
	return client.GetBacktest(ctx, in, opts...)
}

func (m *defaultBacktestService) CancelBacktest(ctx context.Context, in *CancelBacktestRequest, opts ...grpc.CallOption) (*CancelBacktestResponse, error) {
	client := pb.NewBacktestServiceClient(m.cli.Conn())
	return client.CancelBacktest(ctx, in, opts...)
}

func (m *defaultBacktestService) GetReport(ctx context.Context, in *GetReportRequest, opts ...grpc.CallOption) (*GetReportResponse, error) {
	client := pb.NewBacktestServiceClient(m.cli.Conn())
	return client.GetReport(ctx, in, opts...)
}

func (m *defaultBacktestService) GetTrades(ctx context.Context, in *GetTradesRequest, opts ...grpc.CallOption) (*GetTradesResponse, error) {
	client := pb.NewBacktestServiceClient(m.cli.Conn())
	return client.GetTrades(ctx, in, opts...)
}

func (m *defaultBacktestService) GetPositions(ctx context.Context, in *GetPositionsRequest, opts ...grpc.CallOption) (*GetPositionsResponse, error) {
	client := pb.NewBacktestServiceClient(m.cli.Conn())
	return client.GetPositions(ctx, in, opts...)
}

func (m *defaultBacktestService) ListBacktests(ctx context.Context, in *ListBacktestsRequest, opts ...grpc.CallOption) (*ListBacktestsResponse, error) {
	client := pb.NewBacktestServiceClient(m.cli.Conn())
	return client.ListBacktests(ctx, in, opts...)
}
