// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.2
// source: api/ranking/v1/ranking.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RankingService_GetRanking_FullMethodName        = "/ranking.RankingService/GetRanking"
	RankingService_GetStrategyRank_FullMethodName   = "/ranking.RankingService/GetStrategyRank"
	RankingService_GetAuthorRank_FullMethodName     = "/ranking.RankingService/GetAuthorRank"
	RankingService_GetHistoryRanking_FullMethodName = "/ranking.RankingService/GetHistoryRanking"
	RankingService_ListSnapshots_FullMethodName     = "/ranking.RankingService/ListSnapshots"
)

// RankingServiceClient is the client API for RankingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RankingServiceClient interface {
	GetRanking(ctx context.Context, in *GetRankingRequest, opts ...grpc.CallOption) (*GetRankingResponse, error)
	GetStrategyRank(ctx context.Context, in *GetStrategyRankRequest, opts ...grpc.CallOption) (*GetStrategyRankResponse, error)
	GetAuthorRank(ctx context.Context, in *GetAuthorRankRequest, opts ...grpc.CallOption) (*GetAuthorRankResponse, error)
	GetHistoryRanking(ctx context.Context, in *GetHistoryRankingRequest, opts ...grpc.CallOption) (*GetHistoryRankingResponse, error)
	ListSnapshots(ctx context.Context, in *ListSnapshotsRequest, opts ...grpc.CallOption) (*ListSnapshotsResponse, error)
}

type rankingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRankingServiceClient(cc grpc.ClientConnInterface) RankingServiceClient {
	return &rankingServiceClient{cc}
}

func (c *rankingServiceClient) GetRanking(ctx context.Context, in *GetRankingRequest, opts ...grpc.CallOption) (*GetRankingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRankingResponse)
	err := c.cc.Invoke(ctx, RankingService_GetRanking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rankingServiceClient) GetStrategyRank(ctx context.Context, in *GetStrategyRankRequest, opts ...grpc.CallOption) (*GetStrategyRankResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStrategyRankResponse)
	err := c.cc.Invoke(ctx, RankingService_GetStrategyRank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rankingServiceClient) GetAuthorRank(ctx context.Context, in *GetAuthorRankRequest, opts ...grpc.CallOption) (*GetAuthorRankResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAuthorRankResponse)
	err := c.cc.Invoke(ctx, RankingService_GetAuthorRank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rankingServiceClient) GetHistoryRanking(ctx context.Context, in *GetHistoryRankingRequest, opts ...grpc.CallOption) (*GetHistoryRankingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHistoryRankingResponse)
	err := c.cc.Invoke(ctx, RankingService_GetHistoryRanking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rankingServiceClient) ListSnapshots(ctx context.Context, in *ListSnapshotsRequest, opts ...grpc.CallOption) (*ListSnapshotsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSnapshotsResponse)
	err := c.cc.Invoke(ctx, RankingService_ListSnapshots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RankingServiceServer is the server API for RankingService service.
// All implementations must embed UnimplementedRankingServiceServer
// for forward compatibility.
type RankingServiceServer interface {
	GetRanking(context.Context, *GetRankingRequest) (*GetRankingResponse, error)
	GetStrategyRank(context.Context, *GetStrategyRankRequest) (*GetStrategyRankResponse, error)
	GetAuthorRank(context.Context, *GetAuthorRankRequest) (*GetAuthorRankResponse, error)
	GetHistoryRanking(context.Context, *GetHistoryRankingRequest) (*GetHistoryRankingResponse, error)
	ListSnapshots(context.Context, *ListSnapshotsRequest) (*ListSnapshotsResponse, error)
	mustEmbedUnimplementedRankingServiceServer()
}

// UnimplementedRankingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRankingServiceServer struct{}

func (UnimplementedRankingServiceServer) GetRanking(context.Context, *GetRankingRequest) (*GetRankingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRanking not implemented")
}
func (UnimplementedRankingServiceServer) GetStrategyRank(context.Context, *GetStrategyRankRequest) (*GetStrategyRankResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStrategyRank not implemented")
}
func (UnimplementedRankingServiceServer) GetAuthorRank(context.Context, *GetAuthorRankRequest) (*GetAuthorRankResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAuthorRank not implemented")
}
func (UnimplementedRankingServiceServer) GetHistoryRanking(context.Context, *GetHistoryRankingRequest) (*GetHistoryRankingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHistoryRanking not implemented")
}
func (UnimplementedRankingServiceServer) ListSnapshots(context.Context, *ListSnapshotsRequest) (*ListSnapshotsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSnapshots not implemented")
}
func (UnimplementedRankingServiceServer) mustEmbedUnimplementedRankingServiceServer() {}
func (UnimplementedRankingServiceServer) testEmbeddedByValue()                        {}

// UnsafeRankingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RankingServiceServer will
// result in compilation errors.
type UnsafeRankingServiceServer interface {
	mustEmbedUnimplementedRankingServiceServer()
}

func RegisterRankingServiceServer(s grpc.ServiceRegistrar, srv RankingServiceServer) {
	// If the following call panics, it indicates UnimplementedRankingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RankingService_ServiceDesc, srv)
}

func _RankingService_GetRanking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRankingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankingServiceServer).GetRanking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RankingService_GetRanking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankingServiceServer).GetRanking(ctx, req.(*GetRankingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RankingService_GetStrategyRank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStrategyRankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankingServiceServer).GetStrategyRank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RankingService_GetStrategyRank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankingServiceServer).GetStrategyRank(ctx, req.(*GetStrategyRankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RankingService_GetAuthorRank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuthorRankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankingServiceServer).GetAuthorRank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RankingService_GetAuthorRank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankingServiceServer).GetAuthorRank(ctx, req.(*GetAuthorRankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RankingService_GetHistoryRanking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHistoryRankingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankingServiceServer).GetHistoryRanking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RankingService_GetHistoryRanking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankingServiceServer).GetHistoryRanking(ctx, req.(*GetHistoryRankingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RankingService_ListSnapshots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSnapshotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankingServiceServer).ListSnapshots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RankingService_ListSnapshots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankingServiceServer).ListSnapshots(ctx, req.(*ListSnapshotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RankingService_ServiceDesc is the grpc.ServiceDesc for RankingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RankingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ranking.RankingService",
	HandlerType: (*RankingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRanking",
			Handler:    _RankingService_GetRanking_Handler,
		},
		{
			MethodName: "GetStrategyRank",
			Handler:    _RankingService_GetStrategyRank_Handler,
		},
		{
			MethodName: "GetAuthorRank",
			Handler:    _RankingService_GetAuthorRank_Handler,
		},
		{
			MethodName: "GetHistoryRanking",
			Handler:    _RankingService_GetHistoryRanking_Handler,
		},
		{
			MethodName: "ListSnapshots",
			Handler:    _RankingService_ListSnapshots_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/ranking/v1/ranking.proto",
}
