// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: portfolio.proto

package portfolioservice

import (
	"context"

	"github.com/agoXQ/QuantLab/app/portfolio/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddItemRequest           = pb.AddItemRequest
	AddItemResponse          = pb.AddItemResponse
	CreatePortfolioRequest   = pb.CreatePortfolioRequest
	CreatePortfolioResponse  = pb.CreatePortfolioResponse
	DeletePortfolioRequest   = pb.DeletePortfolioRequest
	DeletePortfolioResponse  = pb.DeletePortfolioResponse
	EquityPoint              = pb.EquityPoint
	GetAnalyticsRequest      = pb.GetAnalyticsRequest
	GetAnalyticsResponse     = pb.GetAnalyticsResponse
	GetEquityCurveRequest    = pb.GetEquityCurveRequest
	GetEquityCurveResponse   = pb.GetEquityCurveResponse
	GetPortfolioRequest      = pb.GetPortfolioRequest
	GetPortfolioResponse     = pb.GetPortfolioResponse
	ListPortfoliosRequest    = pb.ListPortfoliosRequest
	ListPortfoliosResponse   = pb.ListPortfoliosResponse
	Portfolio                = pb.Portfolio
	PortfolioAnalytics       = pb.PortfolioAnalytics
	PortfolioItem            = pb.PortfolioItem
	PublishPortfolioRequest  = pb.PublishPortfolioRequest
	PublishPortfolioResponse = pb.PublishPortfolioResponse
	RebalanceRule            = pb.RebalanceRule
	RemoveItemRequest        = pb.RemoveItemRequest
	RemoveItemResponse       = pb.RemoveItemResponse
	UpdatePortfolioRequest   = pb.UpdatePortfolioRequest
	UpdatePortfolioResponse  = pb.UpdatePortfolioResponse
	UpdateWeightsRequest     = pb.UpdateWeightsRequest
	UpdateWeightsResponse    = pb.UpdateWeightsResponse
	WeightItem               = pb.WeightItem

	PortfolioService interface {
		CreatePortfolio(ctx context.Context, in *CreatePortfolioRequest, opts ...grpc.CallOption) (*CreatePortfolioResponse, error)
		GetPortfolio(ctx context.Context, in *GetPortfolioRequest, opts ...grpc.CallOption) (*GetPortfolioResponse, error)
		UpdatePortfolio(ctx context.Context, in *UpdatePortfolioRequest, opts ...grpc.CallOption) (*UpdatePortfolioResponse, error)
		DeletePortfolio(ctx context.Context, in *DeletePortfolioRequest, opts ...grpc.CallOption) (*DeletePortfolioResponse, error)
		AddItem(ctx context.Context, in *AddItemRequest, opts ...grpc.CallOption) (*AddItemResponse, error)
		RemoveItem(ctx context.Context, in *RemoveItemRequest, opts ...grpc.CallOption) (*RemoveItemResponse, error)
		UpdateWeights(ctx context.Context, in *UpdateWeightsRequest, opts ...grpc.CallOption) (*UpdateWeightsResponse, error)
		PublishPortfolio(ctx context.Context, in *PublishPortfolioRequest, opts ...grpc.CallOption) (*PublishPortfolioResponse, error)
		GetAnalytics(ctx context.Context, in *GetAnalyticsRequest, opts ...grpc.CallOption) (*GetAnalyticsResponse, error)
		GetEquityCurve(ctx context.Context, in *GetEquityCurveRequest, opts ...grpc.CallOption) (*GetEquityCurveResponse, error)
		ListPortfolios(ctx context.Context, in *ListPortfoliosRequest, opts ...grpc.CallOption) (*ListPortfoliosResponse, error)
	}

	defaultPortfolioService struct {
		cli zrpc.Client
	}
)

func NewPortfolioService(cli zrpc.Client) PortfolioService {
	return &defaultPortfolioService{
		cli: cli,
	}
}

func (m *defaultPortfolioService) CreatePortfolio(ctx context.Context, in *CreatePortfolioRequest, opts ...grpc.CallOption) (*CreatePortfolioResponse, error) {
	client := pb.NewPortfolioServiceClient(m.cli.Conn())
	return client.CreatePortfolio(ctx, in, opts...)
}

func (m *defaultPortfolioService) GetPortfolio(ctx context.Context, in *GetPortfolioRequest, opts ...grpc.CallOption) (*GetPortfolioResponse, error) {
	client := pb.NewPortfolioServiceClient(m.cli.Conn())
	return client.GetPortfolio(ctx, in, opts...)
}

func (m *defaultPortfolioService) UpdatePortfolio(ctx context.Context, in *UpdatePortfolioRequest, opts ...grpc.CallOption) (*UpdatePortfolioResponse, error) {
	client := pb.NewPortfolioServiceClient(m.cli.Conn())
	return client.UpdatePortfolio(ctx, in, opts...)
}

func (m *defaultPortfolioService) DeletePortfolio(ctx context.Context, in *DeletePortfolioRequest, opts ...grpc.CallOption) (*DeletePortfolioResponse, error) {
	client := pb.NewPortfolioServiceClient(m.cli.Conn())
	return client.DeletePortfolio(ctx, in, opts...)
}

func (m *defaultPortfolioService) AddItem(ctx context.Context, in *AddItemRequest, opts ...grpc.CallOption) (*AddItemResponse, error) {
	client := pb.NewPortfolioServiceClient(m.cli.Conn())
	return client.AddItem(ctx, in, opts...)
}

func (m *defaultPortfolioService) RemoveItem(ctx context.Context, in *RemoveItemRequest, opts ...grpc.CallOption) (*RemoveItemResponse, error) {
	client := pb.NewPortfolioServiceClient(m.cli.Conn())
	return client.RemoveItem(ctx, in, opts...)
}

func (m *defaultPortfolioService) UpdateWeights(ctx context.Context, in *UpdateWeightsRequest, opts ...grpc.CallOption) (*UpdateWeightsResponse, error) {
	client := pb.NewPortfolioServiceClient(m.cli.Conn())
	return client.UpdateWeights(ctx, in, opts...)
}

func (m *defaultPortfolioService) PublishPortfolio(ctx context.Context, in *PublishPortfolioRequest, opts ...grpc.CallOption) (*PublishPortfolioResponse, error) {
	client := pb.NewPortfolioServiceClient(m.cli.Conn())
	return client.PublishPortfolio(ctx, in, opts...)
}

func (m *defaultPortfolioService) GetAnalytics(ctx context.Context, in *GetAnalyticsRequest, opts ...grpc.CallOption) (*GetAnalyticsResponse, error) {
	client := pb.NewPortfolioServiceClient(m.cli.Conn())
	return client.GetAnalytics(ctx, in, opts...)
}

func (m *defaultPortfolioService) GetEquityCurve(ctx context.Context, in *GetEquityCurveRequest, opts ...grpc.CallOption) (*GetEquityCurveResponse, error) {
	client := pb.NewPortfolioServiceClient(m.cli.Conn())
	return client.GetEquityCurve(ctx, in, opts...)
}

func (m *defaultPortfolioService) ListPortfolios(ctx context.Context, in *ListPortfoliosRequest, opts ...grpc.CallOption) (*ListPortfoliosResponse, error) {
	client := pb.NewPortfolioServiceClient(m.cli.Conn())
	return client.ListPortfolios(ctx, in, opts...)
}
