// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: notification.proto

package notificationservice

import (
	"context"

	"github.com/agoXQ/QuantLab/app/notification/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CancelSubscriptionRequest  = pb.CancelSubscriptionRequest
	CancelSubscriptionResponse = pb.CancelSubscriptionResponse
	CreateSubscriptionRequest  = pb.CreateSubscriptionRequest
	CreateSubscriptionResponse = pb.CreateSubscriptionResponse
	DeleteNotificationRequest  = pb.DeleteNotificationRequest
	DeleteNotificationResponse = pb.DeleteNotificationResponse
	GetPreferencesRequest      = pb.GetPreferencesRequest
	GetPreferencesResponse     = pb.GetPreferencesResponse
	GetUnreadCountRequest      = pb.GetUnreadCountRequest
	GetUnreadCountResponse     = pb.GetUnreadCountResponse
	ListNotificationsRequest   = pb.ListNotificationsRequest
	ListNotificationsResponse  = pb.ListNotificationsResponse
	ListSubscriptionsRequest   = pb.ListSubscriptionsRequest
	ListSubscriptionsResponse  = pb.ListSubscriptionsResponse
	MarkAllReadRequest         = pb.MarkAllReadRequest
	MarkAllReadResponse        = pb.MarkAllReadResponse
	MarkReadRequest            = pb.MarkReadRequest
	MarkReadResponse           = pb.MarkReadResponse
	Notification               = pb.Notification
	NotificationPreference     = pb.NotificationPreference
	NotificationSubscription   = pb.NotificationSubscription
	UpdatePreferencesRequest   = pb.UpdatePreferencesRequest
	UpdatePreferencesResponse  = pb.UpdatePreferencesResponse

	NotificationService interface {
		ListNotifications(ctx context.Context, in *ListNotificationsRequest, opts ...grpc.CallOption) (*ListNotificationsResponse, error)
		GetUnreadCount(ctx context.Context, in *GetUnreadCountRequest, opts ...grpc.CallOption) (*GetUnreadCountResponse, error)
		MarkRead(ctx context.Context, in *MarkReadRequest, opts ...grpc.CallOption) (*MarkReadResponse, error)
		MarkAllRead(ctx context.Context, in *MarkAllReadRequest, opts ...grpc.CallOption) (*MarkAllReadResponse, error)
		DeleteNotification(ctx context.Context, in *DeleteNotificationRequest, opts ...grpc.CallOption) (*DeleteNotificationResponse, error)
		GetPreferences(ctx context.Context, in *GetPreferencesRequest, opts ...grpc.CallOption) (*GetPreferencesResponse, error)
		UpdatePreferences(ctx context.Context, in *UpdatePreferencesRequest, opts ...grpc.CallOption) (*UpdatePreferencesResponse, error)
		CreateSubscription(ctx context.Context, in *CreateSubscriptionRequest, opts ...grpc.CallOption) (*CreateSubscriptionResponse, error)
		CancelSubscription(ctx context.Context, in *CancelSubscriptionRequest, opts ...grpc.CallOption) (*CancelSubscriptionResponse, error)
		ListSubscriptions(ctx context.Context, in *ListSubscriptionsRequest, opts ...grpc.CallOption) (*ListSubscriptionsResponse, error)
	}

	defaultNotificationService struct {
		cli zrpc.Client
	}
)

func NewNotificationService(cli zrpc.Client) NotificationService {
	return &defaultNotificationService{
		cli: cli,
	}
}

func (m *defaultNotificationService) ListNotifications(ctx context.Context, in *ListNotificationsRequest, opts ...grpc.CallOption) (*ListNotificationsResponse, error) {
	client := pb.NewNotificationServiceClient(m.cli.Conn())
	return client.ListNotifications(ctx, in, opts...)
}

func (m *defaultNotificationService) GetUnreadCount(ctx context.Context, in *GetUnreadCountRequest, opts ...grpc.CallOption) (*GetUnreadCountResponse, error) {
	client := pb.NewNotificationServiceClient(m.cli.Conn())
	return client.GetUnreadCount(ctx, in, opts...)
}

func (m *defaultNotificationService) MarkRead(ctx context.Context, in *MarkReadRequest, opts ...grpc.CallOption) (*MarkReadResponse, error) {
	client := pb.NewNotificationServiceClient(m.cli.Conn())
	return client.MarkRead(ctx, in, opts...)
}

func (m *defaultNotificationService) MarkAllRead(ctx context.Context, in *MarkAllReadRequest, opts ...grpc.CallOption) (*MarkAllReadResponse, error) {
	client := pb.NewNotificationServiceClient(m.cli.Conn())
	return client.MarkAllRead(ctx, in, opts...)
}

func (m *defaultNotificationService) DeleteNotification(ctx context.Context, in *DeleteNotificationRequest, opts ...grpc.CallOption) (*DeleteNotificationResponse, error) {
	client := pb.NewNotificationServiceClient(m.cli.Conn())
	return client.DeleteNotification(ctx, in, opts...)
}

func (m *defaultNotificationService) GetPreferences(ctx context.Context, in *GetPreferencesRequest, opts ...grpc.CallOption) (*GetPreferencesResponse, error) {
	client := pb.NewNotificationServiceClient(m.cli.Conn())
	return client.GetPreferences(ctx, in, opts...)
}

func (m *defaultNotificationService) UpdatePreferences(ctx context.Context, in *UpdatePreferencesRequest, opts ...grpc.CallOption) (*UpdatePreferencesResponse, error) {
	client := pb.NewNotificationServiceClient(m.cli.Conn())
	return client.UpdatePreferences(ctx, in, opts...)
}

func (m *defaultNotificationService) CreateSubscription(ctx context.Context, in *CreateSubscriptionRequest, opts ...grpc.CallOption) (*CreateSubscriptionResponse, error) {
	client := pb.NewNotificationServiceClient(m.cli.Conn())
	return client.CreateSubscription(ctx, in, opts...)
}

func (m *defaultNotificationService) CancelSubscription(ctx context.Context, in *CancelSubscriptionRequest, opts ...grpc.CallOption) (*CancelSubscriptionResponse, error) {
	client := pb.NewNotificationServiceClient(m.cli.Conn())
	return client.CancelSubscription(ctx, in, opts...)
}

func (m *defaultNotificationService) ListSubscriptions(ctx context.Context, in *ListSubscriptionsRequest, opts ...grpc.CallOption) (*ListSubscriptionsResponse, error) {
	client := pb.NewNotificationServiceClient(m.cli.Conn())
	return client.ListSubscriptions(ctx, in, opts...)
}
