// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/backtest/v1/backtest.proto

package pb

import (
	v1 "github.com/agoXQ/QuantLab/api/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BacktestJob struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StrategyId     int64                  `protobuf:"varint,2,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	VersionId      int64                  `protobuf:"varint,3,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	UserId         int64                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status         string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	StartDate      string                 `protobuf:"bytes,6,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate        string                 `protobuf:"bytes,7,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Benchmark      string                 `protobuf:"bytes,8,opt,name=benchmark,proto3" json:"benchmark,omitempty"`
	InitialCapital float64                `protobuf:"fixed64,9,opt,name=initial_capital,json=initialCapital,proto3" json:"initial_capital,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	FinishedAt     int64                  `protobuf:"varint,11,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BacktestJob) Reset() {
	*x = BacktestJob{}
	mi := &file_api_backtest_v1_backtest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BacktestJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BacktestJob) ProtoMessage() {}

func (x *BacktestJob) ProtoReflect() protoreflect.Message {
	mi := &file_api_backtest_v1_backtest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BacktestJob.ProtoReflect.Descriptor instead.
func (*BacktestJob) Descriptor() ([]byte, []int) {
	return file_api_backtest_v1_backtest_proto_rawDescGZIP(), []int{0}
}

func (x *BacktestJob) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BacktestJob) GetStrategyId() int64 {
	if x != nil {
		return x.StrategyId
	}
	return 0
}

func (x *BacktestJob) GetVersionId() int64 {
	if x != nil {
		return x.VersionId
	}
	return 0
}

func (x *BacktestJob) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BacktestJob) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BacktestJob) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *BacktestJob) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *BacktestJob) GetBenchmark() string {
	if x != nil {
		return x.Benchmark
	}
	return ""
}

func (x *BacktestJob) GetInitialCapital() float64 {
	if x != nil {
		return x.InitialCapital
	}
	return 0
}

func (x *BacktestJob) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *BacktestJob) GetFinishedAt() int64 {
	if x != nil {
		return x.FinishedAt
	}
	return 0
}

type BacktestConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	JobId            int64                  `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	CommissionRate   float64                `protobuf:"fixed64,2,opt,name=commission_rate,json=commissionRate,proto3" json:"commission_rate,omitempty"`
	SlippageRate     float64                `protobuf:"fixed64,3,opt,name=slippage_rate,json=slippageRate,proto3" json:"slippage_rate,omitempty"`
	TaxRate          float64                `protobuf:"fixed64,4,opt,name=tax_rate,json=taxRate,proto3" json:"tax_rate,omitempty"`
	RebalancePeriod  string                 `protobuf:"bytes,5,opt,name=rebalance_period,json=rebalancePeriod,proto3" json:"rebalance_period,omitempty"`
	MaxPositionCount int32                  `protobuf:"varint,6,opt,name=max_position_count,json=maxPositionCount,proto3" json:"max_position_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BacktestConfig) Reset() {
	*x = BacktestConfig{}
	mi := &file_api_backtest_v1_backtest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BacktestConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BacktestConfig) ProtoMessage() {}

func (x *BacktestConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_backtest_v1_backtest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BacktestConfig.ProtoReflect.Descriptor instead.
func (*BacktestConfig) Descriptor() ([]byte, []int) {
	return file_api_backtest_v1_backtest_proto_rawDescGZIP(), []int{1}
}

func (x *BacktestConfig) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *BacktestConfig) GetCommissionRate() float64 {
	if x != nil {
		return x.CommissionRate
	}
	return 0
}

func (x *BacktestConfig) GetSlippageRate() float64 {
	if x != nil {
		return x.SlippageRate
	}
	return 0
}

func (x *BacktestConfig) GetTaxRate() float64 {
	if x != nil {
		return x.TaxRate
	}
	return 0
}

func (x *BacktestConfig) GetRebalancePeriod() string {
	if x != nil {
		return x.RebalancePeriod
	}
	return ""
}

func (x *BacktestConfig) GetMaxPositionCount() int32 {
	if x != nil {
		return x.MaxPositionCount
	}
	return 0
}

type PerformanceReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         int64                  `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	AnnualReturn  float64                `protobuf:"fixed64,2,opt,name=annual_return,json=annualReturn,proto3" json:"annual_return,omitempty"`
	TotalReturn   float64                `protobuf:"fixed64,3,opt,name=total_return,json=totalReturn,proto3" json:"total_return,omitempty"`
	SharpeRatio   float64                `protobuf:"fixed64,4,opt,name=sharpe_ratio,json=sharpeRatio,proto3" json:"sharpe_ratio,omitempty"`
	MaxDrawdown   float64                `protobuf:"fixed64,5,opt,name=max_drawdown,json=maxDrawdown,proto3" json:"max_drawdown,omitempty"`
	WinRate       float64                `protobuf:"fixed64,6,opt,name=win_rate,json=winRate,proto3" json:"win_rate,omitempty"`
	Volatility    float64                `protobuf:"fixed64,7,opt,name=volatility,proto3" json:"volatility,omitempty"`
	Beta          float64                `protobuf:"fixed64,8,opt,name=beta,proto3" json:"beta,omitempty"`
	Alpha         float64                `protobuf:"fixed64,9,opt,name=alpha,proto3" json:"alpha,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PerformanceReport) Reset() {
	*x = PerformanceReport{}
	mi := &file_api_backtest_v1_backtest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerformanceReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerformanceReport) ProtoMessage() {}

func (x *PerformanceReport) ProtoReflect() protoreflect.Message {
	mi := &file_api_backtest_v1_backtest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerformanceReport.ProtoReflect.Descriptor instead.
func (*PerformanceReport) Descriptor() ([]byte, []int) {
	return file_api_backtest_v1_backtest_proto_rawDescGZIP(), []int{2}
}

func (x *PerformanceReport) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *PerformanceReport) GetAnnualReturn() float64 {
	if x != nil {
		return x.AnnualReturn
	}
	return 0
}

func (x *PerformanceReport) GetTotalReturn() float64 {
	if x != nil {
		return x.TotalReturn
	}
	return 0
}

func (x *PerformanceReport) GetSharpeRatio() float64 {
	if x != nil {
		return x.SharpeRatio
	}
	return 0
}

func (x *PerformanceReport) GetMaxDrawdown() float64 {
	if x != nil {
		return x.MaxDrawdown
	}
	return 0
}

func (x *PerformanceReport) GetWinRate() float64 {
	if x != nil {
		return x.WinRate
	}
	return 0
}

func (x *PerformanceReport) GetVolatility() float64 {
	if x != nil {
		return x.Volatility
	}
	return 0
}

func (x *PerformanceReport) GetBeta() float64 {
	if x != nil {
		return x.Beta
	}
	return 0
}

func (x *PerformanceReport) GetAlpha() float64 {
	if x != nil {
		return x.Alpha
	}
	return 0
}

type Trade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	StockCode     string                 `protobuf:"bytes,3,opt,name=stock_code,json=stockCode,proto3" json:"stock_code,omitempty"`
	Quantity      int64                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Commission    float64                `protobuf:"fixed64,6,opt,name=commission,proto3" json:"commission,omitempty"`
	TradeTime     int64                  `protobuf:"varint,7,opt,name=trade_time,json=tradeTime,proto3" json:"trade_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trade) Reset() {
	*x = Trade{}
	mi := &file_api_backtest_v1_backtest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trade) ProtoMessage() {}

func (x *Trade) ProtoReflect() protoreflect.Message {
	mi := &file_api_backtest_v1_backtest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trade.ProtoReflect.Descriptor instead.
func (*Trade) Descriptor() ([]byte, []int) {
	return file_api_backtest_v1_backtest_proto_rawDescGZIP(), []int{3}
}

func (x *Trade) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Trade) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *Trade) GetStockCode() string {
	if x != nil {
		return x.StockCode
	}
	return ""
}

func (x *Trade) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Trade) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Trade) GetCommission() float64 {
	if x != nil {
		return x.Commission
	}
	return 0
}

func (x *Trade) GetTradeTime() int64 {
	if x != nil {
		return x.TradeTime
	}
	return 0
}

type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	JobId         int64                  `protobuf:"varint,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	StockCode     string                 `protobuf:"bytes,3,opt,name=stock_code,json=stockCode,proto3" json:"stock_code,omitempty"`
	Quantity      int64                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	CostPrice     float64                `protobuf:"fixed64,5,opt,name=cost_price,json=costPrice,proto3" json:"cost_price,omitempty"`
	MarketPrice   float64                `protobuf:"fixed64,6,opt,name=market_price,json=marketPrice,proto3" json:"market_price,omitempty"`
	MarketValue   float64                `protobuf:"fixed64,7,opt,name=market_value,json=marketValue,proto3" json:"market_value,omitempty"`
	TradeDate     string                 `protobuf:"bytes,8,opt,name=trade_date,json=tradeDate,proto3" json:"trade_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_api_backtest_v1_backtest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_api_backtest_v1_backtest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_api_backtest_v1_backtest_proto_rawDescGZIP(), []int{4}
}

func (x *Position) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Position) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *Position) GetStockCode() string {
	if x != nil {
		return x.StockCode
	}
	return ""
}

func (x *Position) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Position) GetCostPrice() float64 {
	if x != nil {
		return x.CostPrice
	}
	return 0
}

func (x *Position) GetMarketPrice() float64 {
	if x != nil {
		return x.MarketPrice
	}
	return 0
}

func (x *Position) GetMarketValue() float64 {
	if x != nil {
		return x.MarketValue
	}
	return 0
}

func (x *Position) GetTradeDate() string {
	if x != nil {
		return x.TradeDate
	}
	return ""
}

type CreateBacktestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrategyId    int64                  `protobuf:"varint,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	VersionId     int64                  `protobuf:"varint,2,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	StartDate     string                 `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBacktestRequest) Reset() {
	*x = CreateBacktestRequest{}
	mi := &file_api_backtest_v1_backtest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBacktestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBacktestRequest) ProtoMessage() {}

func (x *CreateBacktestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_backtest_v1_backtest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBacktestRequest.ProtoReflect.Descriptor instead.
func (*CreateBacktestRequest) Descriptor() ([]byte, []int) {
	return file_api_backtest_v1_backtest_proto_rawDescGZIP(), []int{5}
}

func (x *CreateBacktestRequest) GetStrategyId() int64 {
	if x != nil {
		return x.StrategyId
	}
	return 0
}

func (x *CreateBacktestRequest) GetVersionId() int64 {
	if x != nil {
		return x.VersionId
	}
	return 0
}

func (x *CreateBacktestRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *CreateBacktestRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type CreateBacktestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         int64                  `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBacktestResponse) Reset() {
	*x = CreateBacktestResponse{}
	mi := &file_api_backtest_v1_backtest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBacktestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBacktestResponse) ProtoMessage() {}

func (x *CreateBacktestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_backtest_v1_backtest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBacktestResponse.ProtoReflect.Descriptor instead.
func (*CreateBacktestResponse) Descriptor() ([]byte, []int) {
	return file_api_backtest_v1_backtest_proto_rawDescGZIP(), []int{6}
}

func (x *CreateBacktestResponse) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

type GetBacktestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         int64                  `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBacktestRequest) Reset() {
	*x = GetBacktestRequest{}
	mi := &file_api_backtest_v1_backtest_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBacktestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBacktestRequest) ProtoMessage() {}

func (x *GetBacktestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_backtest_v1_backtest_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBacktestRequest.ProtoReflect.Descriptor instead.
func (*GetBacktestRequest) Descriptor() ([]byte, []int) {
	return file_api_backtest_v1_backtest_proto_rawDescGZIP(), []int{7}
}

func (x *GetBacktestRequest) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

type GetBacktestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *BacktestJob           `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	Config        *BacktestConfig        `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBacktestResponse) Reset() {
	*x = GetBacktestResponse{}
	mi := &file_api_backtest_v1_backtest_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBacktestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBacktestResponse) ProtoMessage() {}

func (x *GetBacktestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_backtest_v1_backtest_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBacktestResponse.ProtoReflect.Descriptor instead.
func (*GetBacktestResponse) Descriptor() ([]byte, []int) {
	return file_api_backtest_v1_backtest_proto_rawDescGZIP(), []int{8}
}

func (x *GetBacktestResponse) GetJob() *BacktestJob {
	if x != nil {
		return x.Job
	}
	return nil
}

func (x *GetBacktestResponse) GetConfig() *BacktestConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type CancelBacktestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         int64                  `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBacktestRequest) Reset() {
	*x = CancelBacktestRequest{}
	mi := &file_api_backtest_v1_backtest_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBacktestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBacktestRequest) ProtoMessage() {}

func (x *CancelBacktestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_backtest_v1_backtest_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBacktestRequest.ProtoReflect.Descriptor instead.
func (*CancelBacktestRequest) Descriptor() ([]byte, []int) {
	return file_api_backtest_v1_backtest_proto_rawDescGZIP(), []int{9}
}

func (x *CancelBacktestRequest) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

type CancelBacktestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBacktestResponse) Reset() {
	*x = CancelBacktestResponse{}
	mi := &file_api_backtest_v1_backtest_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBacktestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBacktestResponse) ProtoMessage() {}

func (x *CancelBacktestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_backtest_v1_backtest_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBacktestResponse.ProtoReflect.Descriptor instead.
func (*CancelBacktestResponse) Descriptor() ([]byte, []int) {
	return file_api_backtest_v1_backtest_proto_rawDescGZIP(), []int{10}
}

type GetReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         int64                  `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReportRequest) Reset() {
	*x = GetReportRequest{}
	mi := &file_api_backtest_v1_backtest_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReportRequest) ProtoMessage() {}

func (x *GetReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_backtest_v1_backtest_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReportRequest.ProtoReflect.Descriptor instead.
func (*GetReportRequest) Descriptor() ([]byte, []int) {
	return file_api_backtest_v1_backtest_proto_rawDescGZIP(), []int{11}
}

func (x *GetReportRequest) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

type GetReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report        *PerformanceReport     `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReportResponse) Reset() {
	*x = GetReportResponse{}
	mi := &file_api_backtest_v1_backtest_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReportResponse) ProtoMessage() {}

func (x *GetReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_backtest_v1_backtest_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReportResponse.ProtoReflect.Descriptor instead.
func (*GetReportResponse) Descriptor() ([]byte, []int) {
	return file_api_backtest_v1_backtest_proto_rawDescGZIP(), []int{12}
}

func (x *GetReportResponse) GetReport() *PerformanceReport {
	if x != nil {
		return x.Report
	}
	return nil
}

type GetTradesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         int64                  `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Cursor        *v1.Cursor             `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTradesRequest) Reset() {
	*x = GetTradesRequest{}
	mi := &file_api_backtest_v1_backtest_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTradesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTradesRequest) ProtoMessage() {}

func (x *GetTradesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_backtest_v1_backtest_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTradesRequest.ProtoReflect.Descriptor instead.
func (*GetTradesRequest) Descriptor() ([]byte, []int) {
	return file_api_backtest_v1_backtest_proto_rawDescGZIP(), []int{13}
}

func (x *GetTradesRequest) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *GetTradesRequest) GetCursor() *v1.Cursor {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *GetTradesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetTradesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trades        []*Trade               `protobuf:"bytes,1,rep,name=trades,proto3" json:"trades,omitempty"`
	Cursor        *v1.Cursor             `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTradesResponse) Reset() {
	*x = GetTradesResponse{}
	mi := &file_api_backtest_v1_backtest_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTradesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTradesResponse) ProtoMessage() {}

func (x *GetTradesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_backtest_v1_backtest_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTradesResponse.ProtoReflect.Descriptor instead.
func (*GetTradesResponse) Descriptor() ([]byte, []int) {
	return file_api_backtest_v1_backtest_proto_rawDescGZIP(), []int{14}
}

func (x *GetTradesResponse) GetTrades() []*Trade {
	if x != nil {
		return x.Trades
	}
	return nil
}

func (x *GetTradesResponse) GetCursor() *v1.Cursor {
	if x != nil {
		return x.Cursor
	}
	return nil
}

type GetPositionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         int64                  `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	TradeDate     string                 `protobuf:"bytes,2,opt,name=trade_date,json=tradeDate,proto3" json:"trade_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPositionsRequest) Reset() {
	*x = GetPositionsRequest{}
	mi := &file_api_backtest_v1_backtest_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPositionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPositionsRequest) ProtoMessage() {}

func (x *GetPositionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_backtest_v1_backtest_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPositionsRequest.ProtoReflect.Descriptor instead.
func (*GetPositionsRequest) Descriptor() ([]byte, []int) {
	return file_api_backtest_v1_backtest_proto_rawDescGZIP(), []int{15}
}

func (x *GetPositionsRequest) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *GetPositionsRequest) GetTradeDate() string {
	if x != nil {
		return x.TradeDate
	}
	return ""
}

type GetPositionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Positions     []*Position            `protobuf:"bytes,1,rep,name=positions,proto3" json:"positions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPositionsResponse) Reset() {
	*x = GetPositionsResponse{}
	mi := &file_api_backtest_v1_backtest_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPositionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPositionsResponse) ProtoMessage() {}

func (x *GetPositionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_backtest_v1_backtest_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPositionsResponse.ProtoReflect.Descriptor instead.
func (*GetPositionsResponse) Descriptor() ([]byte, []int) {
	return file_api_backtest_v1_backtest_proto_rawDescGZIP(), []int{16}
}

func (x *GetPositionsResponse) GetPositions() []*Position {
	if x != nil {
		return x.Positions
	}
	return nil
}

type ListBacktestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Cursor        *v1.Cursor             `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBacktestsRequest) Reset() {
	*x = ListBacktestsRequest{}
	mi := &file_api_backtest_v1_backtest_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBacktestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBacktestsRequest) ProtoMessage() {}

func (x *ListBacktestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_backtest_v1_backtest_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBacktestsRequest.ProtoReflect.Descriptor instead.
func (*ListBacktestsRequest) Descriptor() ([]byte, []int) {
	return file_api_backtest_v1_backtest_proto_rawDescGZIP(), []int{17}
}

func (x *ListBacktestsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListBacktestsRequest) GetCursor() *v1.Cursor {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *ListBacktestsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListBacktestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*BacktestJob         `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	Cursor        *v1.Cursor             `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBacktestsResponse) Reset() {
	*x = ListBacktestsResponse{}
	mi := &file_api_backtest_v1_backtest_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBacktestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBacktestsResponse) ProtoMessage() {}

func (x *ListBacktestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_backtest_v1_backtest_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBacktestsResponse.ProtoReflect.Descriptor instead.
func (*ListBacktestsResponse) Descriptor() ([]byte, []int) {
	return file_api_backtest_v1_backtest_proto_rawDescGZIP(), []int{18}
}

func (x *ListBacktestsResponse) GetJobs() []*BacktestJob {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *ListBacktestsResponse) GetCursor() *v1.Cursor {
	if x != nil {
		return x.Cursor
	}
	return nil
}

var File_api_backtest_v1_backtest_proto protoreflect.FileDescriptor

const file_api_backtest_v1_backtest_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/backtest/v1/backtest.proto\x12\bbacktest\x1a\x1aapi/common/v1/common.proto\"\xcf\x02\n" +
	"\vBacktestJob\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vstrategy_id\x18\x02 \x01(\x03R\n" +
	"strategyId\x12\x1d\n" +
	"\n" +
	"version_id\x18\x03 \x01(\x03R\tversionId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"start_date\x18\x06 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\a \x01(\tR\aendDate\x12\x1c\n" +
	"\tbenchmark\x18\b \x01(\tR\tbenchmark\x12'\n" +
	"\x0finitial_capital\x18\t \x01(\x01R\x0einitialCapital\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\x12\x1f\n" +
	"\vfinished_at\x18\v \x01(\x03R\n" +
	"finishedAt\"\xe9\x01\n" +
	"\x0eBacktestConfig\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x03R\x05jobId\x12'\n" +
	"\x0fcommission_rate\x18\x02 \x01(\x01R\x0ecommissionRate\x12#\n" +
	"\rslippage_rate\x18\x03 \x01(\x01R\fslippageRate\x12\x19\n" +
	"\btax_rate\x18\x04 \x01(\x01R\ataxRate\x12)\n" +
	"\x10rebalance_period\x18\x05 \x01(\tR\x0frebalancePeriod\x12,\n" +
	"\x12max_position_count\x18\x06 \x01(\x05R\x10maxPositionCount\"\x9d\x02\n" +
	"\x11PerformanceReport\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x03R\x05jobId\x12#\n" +
	"\rannual_return\x18\x02 \x01(\x01R\fannualReturn\x12!\n" +
	"\ftotal_return\x18\x03 \x01(\x01R\vtotalReturn\x12!\n" +
	"\fsharpe_ratio\x18\x04 \x01(\x01R\vsharpeRatio\x12!\n" +
	"\fmax_drawdown\x18\x05 \x01(\x01R\vmaxDrawdown\x12\x19\n" +
	"\bwin_rate\x18\x06 \x01(\x01R\awinRate\x12\x1e\n" +
	"\n" +
	"volatility\x18\a \x01(\x01R\n" +
	"volatility\x12\x12\n" +
	"\x04beta\x18\b \x01(\x01R\x04beta\x12\x14\n" +
	"\x05alpha\x18\t \x01(\x01R\x05alpha\"\xc2\x01\n" +
	"\x05Trade\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\x12\x1d\n" +
	"\n" +
	"stock_code\x18\x03 \x01(\tR\tstockCode\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x03R\bquantity\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x1e\n" +
	"\n" +
	"commission\x18\x06 \x01(\x01R\n" +
	"commission\x12\x1d\n" +
	"\n" +
	"trade_time\x18\a \x01(\x03R\ttradeTime\"\xf0\x01\n" +
	"\bPosition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\x03R\x05jobId\x12\x1d\n" +
	"\n" +
	"stock_code\x18\x03 \x01(\tR\tstockCode\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x03R\bquantity\x12\x1d\n" +
	"\n" +
	"cost_price\x18\x05 \x01(\x01R\tcostPrice\x12!\n" +
	"\fmarket_price\x18\x06 \x01(\x01R\vmarketPrice\x12!\n" +
	"\fmarket_value\x18\a \x01(\x01R\vmarketValue\x12\x1d\n" +
	"\n" +
	"trade_date\x18\b \x01(\tR\ttradeDate\"\x91\x01\n" +
	"\x15CreateBacktestRequest\x12\x1f\n" +
	"\vstrategy_id\x18\x01 \x01(\x03R\n" +
	"strategyId\x12\x1d\n" +
	"\n" +
	"version_id\x18\x02 \x01(\x03R\tversionId\x12\x1d\n" +
	"\n" +
	"start_date\x18\x03 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x04 \x01(\tR\aendDate\"/\n" +
	"\x16CreateBacktestResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x03R\x05jobId\"+\n" +
	"\x12GetBacktestRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x03R\x05jobId\"p\n" +
	"\x13GetBacktestResponse\x12'\n" +
	"\x03job\x18\x01 \x01(\v2\x15.backtest.BacktestJobR\x03job\x120\n" +
	"\x06config\x18\x02 \x01(\v2\x18.backtest.BacktestConfigR\x06config\".\n" +
	"\x15CancelBacktestRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x03R\x05jobId\"\x18\n" +
	"\x16CancelBacktestResponse\")\n" +
	"\x10GetReportRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x03R\x05jobId\"H\n" +
	"\x11GetReportResponse\x123\n" +
	"\x06report\x18\x01 \x01(\v2\x1b.backtest.PerformanceReportR\x06report\"g\n" +
	"\x10GetTradesRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x03R\x05jobId\x12&\n" +
	"\x06cursor\x18\x02 \x01(\v2\x0e.common.CursorR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"d\n" +
	"\x11GetTradesResponse\x12'\n" +
	"\x06trades\x18\x01 \x03(\v2\x0f.backtest.TradeR\x06trades\x12&\n" +
	"\x06cursor\x18\x02 \x01(\v2\x0e.common.CursorR\x06cursor\"K\n" +
	"\x13GetPositionsRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x03R\x05jobId\x12\x1d\n" +
	"\n" +
	"trade_date\x18\x02 \x01(\tR\ttradeDate\"H\n" +
	"\x14GetPositionsResponse\x120\n" +
	"\tpositions\x18\x01 \x03(\v2\x12.backtest.PositionR\tpositions\"m\n" +
	"\x14ListBacktestsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12&\n" +
	"\x06cursor\x18\x02 \x01(\v2\x0e.common.CursorR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"j\n" +
	"\x15ListBacktestsResponse\x12)\n" +
	"\x04jobs\x18\x01 \x03(\v2\x15.backtest.BacktestJobR\x04jobs\x12&\n" +
	"\x06cursor\x18\x02 \x01(\v2\x0e.common.CursorR\x06cursor2\xb4\x04\n" +
	"\x0fBacktestService\x12S\n" +
	"\x0eCreateBacktest\x12\x1f.backtest.CreateBacktestRequest\x1a .backtest.CreateBacktestResponse\x12J\n" +
	"\vGetBacktest\x12\x1c.backtest.GetBacktestRequest\x1a\x1d.backtest.GetBacktestResponse\x12S\n" +
	"\x0eCancelBacktest\x12\x1f.backtest.CancelBacktestRequest\x1a .backtest.CancelBacktestResponse\x12D\n" +
	"\tGetReport\x12\x1a.backtest.GetReportRequest\x1a\x1b.backtest.GetReportResponse\x12D\n" +
	"\tGetTrades\x12\x1a.backtest.GetTradesRequest\x1a\x1b.backtest.GetTradesResponse\x12M\n" +
	"\fGetPositions\x12\x1d.backtest.GetPositionsRequest\x1a\x1e.backtest.GetPositionsResponse\x12P\n" +
	"\rListBacktests\x12\x1e.backtest.ListBacktestsRequest\x1a\x1f.backtest.ListBacktestsResponseB+Z)github.com/agoXQ/QuantLab/app/backtest/pbb\x06proto3"

var (
	file_api_backtest_v1_backtest_proto_rawDescOnce sync.Once
	file_api_backtest_v1_backtest_proto_rawDescData []byte
)

func file_api_backtest_v1_backtest_proto_rawDescGZIP() []byte {
	file_api_backtest_v1_backtest_proto_rawDescOnce.Do(func() {
		file_api_backtest_v1_backtest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_backtest_v1_backtest_proto_rawDesc), len(file_api_backtest_v1_backtest_proto_rawDesc)))
	})
	return file_api_backtest_v1_backtest_proto_rawDescData
}

var file_api_backtest_v1_backtest_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_api_backtest_v1_backtest_proto_goTypes = []any{
	(*BacktestJob)(nil),            // 0: backtest.BacktestJob
	(*BacktestConfig)(nil),         // 1: backtest.BacktestConfig
	(*PerformanceReport)(nil),      // 2: backtest.PerformanceReport
	(*Trade)(nil),                  // 3: backtest.Trade
	(*Position)(nil),               // 4: backtest.Position
	(*CreateBacktestRequest)(nil),  // 5: backtest.CreateBacktestRequest
	(*CreateBacktestResponse)(nil), // 6: backtest.CreateBacktestResponse
	(*GetBacktestRequest)(nil),     // 7: backtest.GetBacktestRequest
	(*GetBacktestResponse)(nil),    // 8: backtest.GetBacktestResponse
	(*CancelBacktestRequest)(nil),  // 9: backtest.CancelBacktestRequest
	(*CancelBacktestResponse)(nil), // 10: backtest.CancelBacktestResponse
	(*GetReportRequest)(nil),       // 11: backtest.GetReportRequest
	(*GetReportResponse)(nil),      // 12: backtest.GetReportResponse
	(*GetTradesRequest)(nil),       // 13: backtest.GetTradesRequest
	(*GetTradesResponse)(nil),      // 14: backtest.GetTradesResponse
	(*GetPositionsRequest)(nil),    // 15: backtest.GetPositionsRequest
	(*GetPositionsResponse)(nil),   // 16: backtest.GetPositionsResponse
	(*ListBacktestsRequest)(nil),   // 17: backtest.ListBacktestsRequest
	(*ListBacktestsResponse)(nil),  // 18: backtest.ListBacktestsResponse
	(*v1.Cursor)(nil),              // 19: common.Cursor
}
var file_api_backtest_v1_backtest_proto_depIdxs = []int32{
	0,  // 0: backtest.GetBacktestResponse.job:type_name -> backtest.BacktestJob
	1,  // 1: backtest.GetBacktestResponse.config:type_name -> backtest.BacktestConfig
	2,  // 2: backtest.GetReportResponse.report:type_name -> backtest.PerformanceReport
	19, // 3: backtest.GetTradesRequest.cursor:type_name -> common.Cursor
	3,  // 4: backtest.GetTradesResponse.trades:type_name -> backtest.Trade
	19, // 5: backtest.GetTradesResponse.cursor:type_name -> common.Cursor
	4,  // 6: backtest.GetPositionsResponse.positions:type_name -> backtest.Position
	19, // 7: backtest.ListBacktestsRequest.cursor:type_name -> common.Cursor
	0,  // 8: backtest.ListBacktestsResponse.jobs:type_name -> backtest.BacktestJob
	19, // 9: backtest.ListBacktestsResponse.cursor:type_name -> common.Cursor
	5,  // 10: backtest.BacktestService.CreateBacktest:input_type -> backtest.CreateBacktestRequest
	7,  // 11: backtest.BacktestService.GetBacktest:input_type -> backtest.GetBacktestRequest
	9,  // 12: backtest.BacktestService.CancelBacktest:input_type -> backtest.CancelBacktestRequest
	11, // 13: backtest.BacktestService.GetReport:input_type -> backtest.GetReportRequest
	13, // 14: backtest.BacktestService.GetTrades:input_type -> backtest.GetTradesRequest
	15, // 15: backtest.BacktestService.GetPositions:input_type -> backtest.GetPositionsRequest
	17, // 16: backtest.BacktestService.ListBacktests:input_type -> backtest.ListBacktestsRequest
	6,  // 17: backtest.BacktestService.CreateBacktest:output_type -> backtest.CreateBacktestResponse
	8,  // 18: backtest.BacktestService.GetBacktest:output_type -> backtest.GetBacktestResponse
	10, // 19: backtest.BacktestService.CancelBacktest:output_type -> backtest.CancelBacktestResponse
	12, // 20: backtest.BacktestService.GetReport:output_type -> backtest.GetReportResponse
	14, // 21: backtest.BacktestService.GetTrades:output_type -> backtest.GetTradesResponse
	16, // 22: backtest.BacktestService.GetPositions:output_type -> backtest.GetPositionsResponse
	18, // 23: backtest.BacktestService.ListBacktests:output_type -> backtest.ListBacktestsResponse
	17, // [17:24] is the sub-list for method output_type
	10, // [10:17] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_api_backtest_v1_backtest_proto_init() }
func file_api_backtest_v1_backtest_proto_init() {
	if File_api_backtest_v1_backtest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_backtest_v1_backtest_proto_rawDesc), len(file_api_backtest_v1_backtest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_backtest_v1_backtest_proto_goTypes,
		DependencyIndexes: file_api_backtest_v1_backtest_proto_depIdxs,
		MessageInfos:      file_api_backtest_v1_backtest_proto_msgTypes,
	}.Build()
	File_api_backtest_v1_backtest_proto = out.File
	file_api_backtest_v1_backtest_proto_goTypes = nil
	file_api_backtest_v1_backtest_proto_depIdxs = nil
}
