// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: community.proto

package communityservice

import (
	"context"

	"github.com/agoXQ/QuantLab/app/community/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Comment                   = pb.Comment
	Content                   = pb.Content
	CreateCommentRequest      = pb.CreateCommentRequest
	CreateCommentResponse     = pb.CreateCommentResponse
	CreateContentRequest      = pb.CreateContentRequest
	CreateContentResponse     = pb.CreateContentResponse
	DeleteCommentRequest      = pb.DeleteCommentRequest
	DeleteCommentResponse     = pb.DeleteCommentResponse
	FavoriteContentRequest    = pb.FavoriteContentRequest
	FavoriteContentResponse   = pb.FavoriteContentResponse
	FeedItem                  = pb.FeedItem
	GetContentRequest         = pb.GetContentRequest
	GetContentResponse        = pb.GetContentResponse
	GetFeedRequest            = pb.GetFeedRequest
	GetFeedResponse           = pb.GetFeedResponse
	GetProfileRequest         = pb.GetProfileRequest
	GetProfileResponse        = pb.GetProfileResponse
	LikeContentRequest        = pb.LikeContentRequest
	LikeContentResponse       = pb.LikeContentResponse
	ListCommentsRequest       = pb.ListCommentsRequest
	ListCommentsResponse      = pb.ListCommentsResponse
	ListUserContentsRequest   = pb.ListUserContentsRequest
	ListUserContentsResponse  = pb.ListUserContentsResponse
	UnfavoriteContentRequest  = pb.UnfavoriteContentRequest
	UnfavoriteContentResponse = pb.UnfavoriteContentResponse
	UnlikeContentRequest      = pb.UnlikeContentRequest
	UnlikeContentResponse     = pb.UnlikeContentResponse
	UserProfile               = pb.UserProfile

	CommunityService interface {
		CreateContent(ctx context.Context, in *CreateContentRequest, opts ...grpc.CallOption) (*CreateContentResponse, error)
		GetContent(ctx context.Context, in *GetContentRequest, opts ...grpc.CallOption) (*GetContentResponse, error)
		GetFeed(ctx context.Context, in *GetFeedRequest, opts ...grpc.CallOption) (*GetFeedResponse, error)
		LikeContent(ctx context.Context, in *LikeContentRequest, opts ...grpc.CallOption) (*LikeContentResponse, error)
		UnlikeContent(ctx context.Context, in *UnlikeContentRequest, opts ...grpc.CallOption) (*UnlikeContentResponse, error)
		FavoriteContent(ctx context.Context, in *FavoriteContentRequest, opts ...grpc.CallOption) (*FavoriteContentResponse, error)
		UnfavoriteContent(ctx context.Context, in *UnfavoriteContentRequest, opts ...grpc.CallOption) (*UnfavoriteContentResponse, error)
		CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*CreateCommentResponse, error)
		ListComments(ctx context.Context, in *ListCommentsRequest, opts ...grpc.CallOption) (*ListCommentsResponse, error)
		DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*DeleteCommentResponse, error)
		GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error)
		ListUserContents(ctx context.Context, in *ListUserContentsRequest, opts ...grpc.CallOption) (*ListUserContentsResponse, error)
	}

	defaultCommunityService struct {
		cli zrpc.Client
	}
)

func NewCommunityService(cli zrpc.Client) CommunityService {
	return &defaultCommunityService{
		cli: cli,
	}
}

func (m *defaultCommunityService) CreateContent(ctx context.Context, in *CreateContentRequest, opts ...grpc.CallOption) (*CreateContentResponse, error) {
	client := pb.NewCommunityServiceClient(m.cli.Conn())
	return client.CreateContent(ctx, in, opts...)
}

func (m *defaultCommunityService) GetContent(ctx context.Context, in *GetContentRequest, opts ...grpc.CallOption) (*GetContentResponse, error) {
	client := pb.NewCommunityServiceClient(m.cli.Conn())
	return client.GetContent(ctx, in, opts...)
}

func (m *defaultCommunityService) GetFeed(ctx context.Context, in *GetFeedRequest, opts ...grpc.CallOption) (*GetFeedResponse, error) {
	client := pb.NewCommunityServiceClient(m.cli.Conn())
	return client.GetFeed(ctx, in, opts...)
}

func (m *defaultCommunityService) LikeContent(ctx context.Context, in *LikeContentRequest, opts ...grpc.CallOption) (*LikeContentResponse, error) {
	client := pb.NewCommunityServiceClient(m.cli.Conn())
	return client.LikeContent(ctx, in, opts...)
}

func (m *defaultCommunityService) UnlikeContent(ctx context.Context, in *UnlikeContentRequest, opts ...grpc.CallOption) (*UnlikeContentResponse, error) {
	client := pb.NewCommunityServiceClient(m.cli.Conn())
	return client.UnlikeContent(ctx, in, opts...)
}

func (m *defaultCommunityService) FavoriteContent(ctx context.Context, in *FavoriteContentRequest, opts ...grpc.CallOption) (*FavoriteContentResponse, error) {
	client := pb.NewCommunityServiceClient(m.cli.Conn())
	return client.FavoriteContent(ctx, in, opts...)
}

func (m *defaultCommunityService) UnfavoriteContent(ctx context.Context, in *UnfavoriteContentRequest, opts ...grpc.CallOption) (*UnfavoriteContentResponse, error) {
	client := pb.NewCommunityServiceClient(m.cli.Conn())
	return client.UnfavoriteContent(ctx, in, opts...)
}

func (m *defaultCommunityService) CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*CreateCommentResponse, error) {
	client := pb.NewCommunityServiceClient(m.cli.Conn())
	return client.CreateComment(ctx, in, opts...)
}

func (m *defaultCommunityService) ListComments(ctx context.Context, in *ListCommentsRequest, opts ...grpc.CallOption) (*ListCommentsResponse, error) {
	client := pb.NewCommunityServiceClient(m.cli.Conn())
	return client.ListComments(ctx, in, opts...)
}

func (m *defaultCommunityService) DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*DeleteCommentResponse, error) {
	client := pb.NewCommunityServiceClient(m.cli.Conn())
	return client.DeleteComment(ctx, in, opts...)
}

func (m *defaultCommunityService) GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error) {
	client := pb.NewCommunityServiceClient(m.cli.Conn())
	return client.GetProfile(ctx, in, opts...)
}

func (m *defaultCommunityService) ListUserContents(ctx context.Context, in *ListUserContentsRequest, opts ...grpc.CallOption) (*ListUserContentsResponse, error) {
	client := pb.NewCommunityServiceClient(m.cli.Conn())
	return client.ListUserContents(ctx, in, opts...)
}
