// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: backtest.proto

package server

import (
	"context"

	"github.com/agoXQ/QuantLab/app/backtest/internal/logic"
	"github.com/agoXQ/QuantLab/app/backtest/internal/svc"
	"github.com/agoXQ/QuantLab/app/backtest/pb"
)

type BacktestServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedBacktestServiceServer
}

func NewBacktestServiceServer(svcCtx *svc.ServiceContext) *BacktestServiceServer {
	return &BacktestServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *BacktestServiceServer) CreateBacktest(ctx context.Context, in *pb.CreateBacktestRequest) (*pb.CreateBacktestResponse, error) {
	l := logic.NewCreateBacktestLogic(ctx, s.svcCtx)
	return l.CreateBacktest(in)
}

func (s *BacktestServiceServer) GetBacktest(ctx context.Context, in *pb.GetBacktestRequest) (*pb.GetBacktestResponse, error) {
	l := logic.NewGetBacktestLogic(ctx, s.svcCtx)
	return l.GetBacktest(in)
}

func (s *BacktestServiceServer) CancelBacktest(ctx context.Context, in *pb.CancelBacktestRequest) (*pb.CancelBacktestResponse, error) {
	l := logic.NewCancelBacktestLogic(ctx, s.svcCtx)
	return l.CancelBacktest(in)
}

func (s *BacktestServiceServer) GetReport(ctx context.Context, in *pb.GetReportRequest) (*pb.GetReportResponse, error) {
	l := logic.NewGetReportLogic(ctx, s.svcCtx)
	return l.GetReport(in)
}

func (s *BacktestServiceServer) GetTrades(ctx context.Context, in *pb.GetTradesRequest) (*pb.GetTradesResponse, error) {
	l := logic.NewGetTradesLogic(ctx, s.svcCtx)
	return l.GetTrades(in)
}

func (s *BacktestServiceServer) GetPositions(ctx context.Context, in *pb.GetPositionsRequest) (*pb.GetPositionsResponse, error) {
	l := logic.NewGetPositionsLogic(ctx, s.svcCtx)
	return l.GetPositions(in)
}

func (s *BacktestServiceServer) ListBacktests(ctx context.Context, in *pb.ListBacktestsRequest) (*pb.ListBacktestsResponse, error) {
	l := logic.NewListBacktestsLogic(ctx, s.svcCtx)
	return l.ListBacktests(in)
}
