// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/strategy/v1/strategy.proto

package pb

import (
	v1 "github.com/agoXQ/QuantLab/api/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Strategy struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId         int64                  `protobuf:"varint,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Title            string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description      string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status           v1.Status              `protobuf:"varint,5,opt,name=status,proto3,enum=common.Status" json:"status,omitempty"`
	Visibility       v1.Visibility          `protobuf:"varint,6,opt,name=visibility,proto3,enum=common.Visibility" json:"visibility,omitempty"`
	Category         string                 `protobuf:"bytes,7,opt,name=category,proto3" json:"category,omitempty"`
	Tags             []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	CurrentVersionId int64                  `protobuf:"varint,9,opt,name=current_version_id,json=currentVersionId,proto3" json:"current_version_id,omitempty"`
	ViewCount        int64                  `protobuf:"varint,10,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	FavoriteCount    int64                  `protobuf:"varint,11,opt,name=favorite_count,json=favoriteCount,proto3" json:"favorite_count,omitempty"`
	ForkCount        int64                  `protobuf:"varint,12,opt,name=fork_count,json=forkCount,proto3" json:"fork_count,omitempty"`
	CreatedAt        int64                  `protobuf:"varint,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        int64                  `protobuf:"varint,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Strategy) Reset() {
	*x = Strategy{}
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Strategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Strategy) ProtoMessage() {}

func (x *Strategy) ProtoReflect() protoreflect.Message {
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Strategy.ProtoReflect.Descriptor instead.
func (*Strategy) Descriptor() ([]byte, []int) {
	return file_api_strategy_v1_strategy_proto_rawDescGZIP(), []int{0}
}

func (x *Strategy) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Strategy) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *Strategy) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Strategy) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Strategy) GetStatus() v1.Status {
	if x != nil {
		return x.Status
	}
	return v1.Status(0)
}

func (x *Strategy) GetVisibility() v1.Visibility {
	if x != nil {
		return x.Visibility
	}
	return v1.Visibility(0)
}

func (x *Strategy) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Strategy) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Strategy) GetCurrentVersionId() int64 {
	if x != nil {
		return x.CurrentVersionId
	}
	return 0
}

func (x *Strategy) GetViewCount() int64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *Strategy) GetFavoriteCount() int64 {
	if x != nil {
		return x.FavoriteCount
	}
	return 0
}

func (x *Strategy) GetForkCount() int64 {
	if x != nil {
		return x.ForkCount
	}
	return 0
}

func (x *Strategy) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Strategy) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type StrategyVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StrategyId    int64                  `protobuf:"varint,2,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	VersionNo     string                 `protobuf:"bytes,3,opt,name=version_no,json=versionNo,proto3" json:"version_no,omitempty"`
	FormulaText   string                 `protobuf:"bytes,4,opt,name=formula_text,json=formulaText,proto3" json:"formula_text,omitempty"`
	BuyRule       string                 `protobuf:"bytes,5,opt,name=buy_rule,json=buyRule,proto3" json:"buy_rule,omitempty"`
	SellRule      string                 `protobuf:"bytes,6,opt,name=sell_rule,json=sellRule,proto3" json:"sell_rule,omitempty"`
	RiskRule      string                 `protobuf:"bytes,7,opt,name=risk_rule,json=riskRule,proto3" json:"risk_rule,omitempty"`
	PositionRule  string                 `protobuf:"bytes,8,opt,name=position_rule,json=positionRule,proto3" json:"position_rule,omitempty"`
	RebalanceRule string                 `protobuf:"bytes,9,opt,name=rebalance_rule,json=rebalanceRule,proto3" json:"rebalance_rule,omitempty"`
	ChangeLog     string                 `protobuf:"bytes,10,opt,name=change_log,json=changeLog,proto3" json:"change_log,omitempty"`
	CreatedBy     int64                  `protobuf:"varint,11,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StrategyVersion) Reset() {
	*x = StrategyVersion{}
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StrategyVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrategyVersion) ProtoMessage() {}

func (x *StrategyVersion) ProtoReflect() protoreflect.Message {
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrategyVersion.ProtoReflect.Descriptor instead.
func (*StrategyVersion) Descriptor() ([]byte, []int) {
	return file_api_strategy_v1_strategy_proto_rawDescGZIP(), []int{1}
}

func (x *StrategyVersion) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StrategyVersion) GetStrategyId() int64 {
	if x != nil {
		return x.StrategyId
	}
	return 0
}

func (x *StrategyVersion) GetVersionNo() string {
	if x != nil {
		return x.VersionNo
	}
	return ""
}

func (x *StrategyVersion) GetFormulaText() string {
	if x != nil {
		return x.FormulaText
	}
	return ""
}

func (x *StrategyVersion) GetBuyRule() string {
	if x != nil {
		return x.BuyRule
	}
	return ""
}

func (x *StrategyVersion) GetSellRule() string {
	if x != nil {
		return x.SellRule
	}
	return ""
}

func (x *StrategyVersion) GetRiskRule() string {
	if x != nil {
		return x.RiskRule
	}
	return ""
}

func (x *StrategyVersion) GetPositionRule() string {
	if x != nil {
		return x.PositionRule
	}
	return ""
}

func (x *StrategyVersion) GetRebalanceRule() string {
	if x != nil {
		return x.RebalanceRule
	}
	return ""
}

func (x *StrategyVersion) GetChangeLog() string {
	if x != nil {
		return x.ChangeLog
	}
	return ""
}

func (x *StrategyVersion) GetCreatedBy() int64 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

func (x *StrategyVersion) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type CreateStrategyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStrategyRequest) Reset() {
	*x = CreateStrategyRequest{}
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStrategyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStrategyRequest) ProtoMessage() {}

func (x *CreateStrategyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStrategyRequest.ProtoReflect.Descriptor instead.
func (*CreateStrategyRequest) Descriptor() ([]byte, []int) {
	return file_api_strategy_v1_strategy_proto_rawDescGZIP(), []int{2}
}

func (x *CreateStrategyRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateStrategyRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateStrategyRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateStrategyRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type CreateStrategyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrategyId    int64                  `protobuf:"varint,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStrategyResponse) Reset() {
	*x = CreateStrategyResponse{}
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStrategyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStrategyResponse) ProtoMessage() {}

func (x *CreateStrategyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStrategyResponse.ProtoReflect.Descriptor instead.
func (*CreateStrategyResponse) Descriptor() ([]byte, []int) {
	return file_api_strategy_v1_strategy_proto_rawDescGZIP(), []int{3}
}

func (x *CreateStrategyResponse) GetStrategyId() int64 {
	if x != nil {
		return x.StrategyId
	}
	return 0
}

type GetStrategyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrategyId    int64                  `protobuf:"varint,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStrategyRequest) Reset() {
	*x = GetStrategyRequest{}
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStrategyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStrategyRequest) ProtoMessage() {}

func (x *GetStrategyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStrategyRequest.ProtoReflect.Descriptor instead.
func (*GetStrategyRequest) Descriptor() ([]byte, []int) {
	return file_api_strategy_v1_strategy_proto_rawDescGZIP(), []int{4}
}

func (x *GetStrategyRequest) GetStrategyId() int64 {
	if x != nil {
		return x.StrategyId
	}
	return 0
}

type GetStrategyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Strategy      *Strategy              `protobuf:"bytes,1,opt,name=strategy,proto3" json:"strategy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStrategyResponse) Reset() {
	*x = GetStrategyResponse{}
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStrategyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStrategyResponse) ProtoMessage() {}

func (x *GetStrategyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStrategyResponse.ProtoReflect.Descriptor instead.
func (*GetStrategyResponse) Descriptor() ([]byte, []int) {
	return file_api_strategy_v1_strategy_proto_rawDescGZIP(), []int{5}
}

func (x *GetStrategyResponse) GetStrategy() *Strategy {
	if x != nil {
		return x.Strategy
	}
	return nil
}

type UpdateStrategyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrategyId    int64                  `protobuf:"varint,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStrategyRequest) Reset() {
	*x = UpdateStrategyRequest{}
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStrategyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStrategyRequest) ProtoMessage() {}

func (x *UpdateStrategyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStrategyRequest.ProtoReflect.Descriptor instead.
func (*UpdateStrategyRequest) Descriptor() ([]byte, []int) {
	return file_api_strategy_v1_strategy_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateStrategyRequest) GetStrategyId() int64 {
	if x != nil {
		return x.StrategyId
	}
	return 0
}

func (x *UpdateStrategyRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateStrategyRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateStrategyRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *UpdateStrategyRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type UpdateStrategyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStrategyResponse) Reset() {
	*x = UpdateStrategyResponse{}
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStrategyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStrategyResponse) ProtoMessage() {}

func (x *UpdateStrategyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStrategyResponse.ProtoReflect.Descriptor instead.
func (*UpdateStrategyResponse) Descriptor() ([]byte, []int) {
	return file_api_strategy_v1_strategy_proto_rawDescGZIP(), []int{7}
}

type DeleteStrategyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrategyId    int64                  `protobuf:"varint,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStrategyRequest) Reset() {
	*x = DeleteStrategyRequest{}
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStrategyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStrategyRequest) ProtoMessage() {}

func (x *DeleteStrategyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStrategyRequest.ProtoReflect.Descriptor instead.
func (*DeleteStrategyRequest) Descriptor() ([]byte, []int) {
	return file_api_strategy_v1_strategy_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteStrategyRequest) GetStrategyId() int64 {
	if x != nil {
		return x.StrategyId
	}
	return 0
}

type DeleteStrategyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStrategyResponse) Reset() {
	*x = DeleteStrategyResponse{}
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStrategyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStrategyResponse) ProtoMessage() {}

func (x *DeleteStrategyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStrategyResponse.ProtoReflect.Descriptor instead.
func (*DeleteStrategyResponse) Descriptor() ([]byte, []int) {
	return file_api_strategy_v1_strategy_proto_rawDescGZIP(), []int{9}
}

type PublishStrategyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrategyId    int64                  `protobuf:"varint,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	VersionId     int64                  `protobuf:"varint,2,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishStrategyRequest) Reset() {
	*x = PublishStrategyRequest{}
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishStrategyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishStrategyRequest) ProtoMessage() {}

func (x *PublishStrategyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishStrategyRequest.ProtoReflect.Descriptor instead.
func (*PublishStrategyRequest) Descriptor() ([]byte, []int) {
	return file_api_strategy_v1_strategy_proto_rawDescGZIP(), []int{10}
}

func (x *PublishStrategyRequest) GetStrategyId() int64 {
	if x != nil {
		return x.StrategyId
	}
	return 0
}

func (x *PublishStrategyRequest) GetVersionId() int64 {
	if x != nil {
		return x.VersionId
	}
	return 0
}

type PublishStrategyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishStrategyResponse) Reset() {
	*x = PublishStrategyResponse{}
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishStrategyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishStrategyResponse) ProtoMessage() {}

func (x *PublishStrategyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishStrategyResponse.ProtoReflect.Descriptor instead.
func (*PublishStrategyResponse) Descriptor() ([]byte, []int) {
	return file_api_strategy_v1_strategy_proto_rawDescGZIP(), []int{11}
}

type ArchiveStrategyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrategyId    int64                  `protobuf:"varint,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveStrategyRequest) Reset() {
	*x = ArchiveStrategyRequest{}
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveStrategyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveStrategyRequest) ProtoMessage() {}

func (x *ArchiveStrategyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveStrategyRequest.ProtoReflect.Descriptor instead.
func (*ArchiveStrategyRequest) Descriptor() ([]byte, []int) {
	return file_api_strategy_v1_strategy_proto_rawDescGZIP(), []int{12}
}

func (x *ArchiveStrategyRequest) GetStrategyId() int64 {
	if x != nil {
		return x.StrategyId
	}
	return 0
}

type ArchiveStrategyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveStrategyResponse) Reset() {
	*x = ArchiveStrategyResponse{}
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveStrategyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveStrategyResponse) ProtoMessage() {}

func (x *ArchiveStrategyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveStrategyResponse.ProtoReflect.Descriptor instead.
func (*ArchiveStrategyResponse) Descriptor() ([]byte, []int) {
	return file_api_strategy_v1_strategy_proto_rawDescGZIP(), []int{13}
}

type ForkStrategyRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SourceStrategyId int64                  `protobuf:"varint,1,opt,name=source_strategy_id,json=sourceStrategyId,proto3" json:"source_strategy_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ForkStrategyRequest) Reset() {
	*x = ForkStrategyRequest{}
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForkStrategyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForkStrategyRequest) ProtoMessage() {}

func (x *ForkStrategyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForkStrategyRequest.ProtoReflect.Descriptor instead.
func (*ForkStrategyRequest) Descriptor() ([]byte, []int) {
	return file_api_strategy_v1_strategy_proto_rawDescGZIP(), []int{14}
}

func (x *ForkStrategyRequest) GetSourceStrategyId() int64 {
	if x != nil {
		return x.SourceStrategyId
	}
	return 0
}

type ForkStrategyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewStrategyId int64                  `protobuf:"varint,1,opt,name=new_strategy_id,json=newStrategyId,proto3" json:"new_strategy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForkStrategyResponse) Reset() {
	*x = ForkStrategyResponse{}
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForkStrategyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForkStrategyResponse) ProtoMessage() {}

func (x *ForkStrategyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForkStrategyResponse.ProtoReflect.Descriptor instead.
func (*ForkStrategyResponse) Descriptor() ([]byte, []int) {
	return file_api_strategy_v1_strategy_proto_rawDescGZIP(), []int{15}
}

func (x *ForkStrategyResponse) GetNewStrategyId() int64 {
	if x != nil {
		return x.NewStrategyId
	}
	return 0
}

type CreateVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrategyId    int64                  `protobuf:"varint,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	FormulaText   string                 `protobuf:"bytes,2,opt,name=formula_text,json=formulaText,proto3" json:"formula_text,omitempty"`
	BuyRule       string                 `protobuf:"bytes,3,opt,name=buy_rule,json=buyRule,proto3" json:"buy_rule,omitempty"`
	SellRule      string                 `protobuf:"bytes,4,opt,name=sell_rule,json=sellRule,proto3" json:"sell_rule,omitempty"`
	RiskRule      string                 `protobuf:"bytes,5,opt,name=risk_rule,json=riskRule,proto3" json:"risk_rule,omitempty"`
	PositionRule  string                 `protobuf:"bytes,6,opt,name=position_rule,json=positionRule,proto3" json:"position_rule,omitempty"`
	RebalanceRule string                 `protobuf:"bytes,7,opt,name=rebalance_rule,json=rebalanceRule,proto3" json:"rebalance_rule,omitempty"`
	ChangeLog     string                 `protobuf:"bytes,8,opt,name=change_log,json=changeLog,proto3" json:"change_log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVersionRequest) Reset() {
	*x = CreateVersionRequest{}
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVersionRequest) ProtoMessage() {}

func (x *CreateVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVersionRequest.ProtoReflect.Descriptor instead.
func (*CreateVersionRequest) Descriptor() ([]byte, []int) {
	return file_api_strategy_v1_strategy_proto_rawDescGZIP(), []int{16}
}

func (x *CreateVersionRequest) GetStrategyId() int64 {
	if x != nil {
		return x.StrategyId
	}
	return 0
}

func (x *CreateVersionRequest) GetFormulaText() string {
	if x != nil {
		return x.FormulaText
	}
	return ""
}

func (x *CreateVersionRequest) GetBuyRule() string {
	if x != nil {
		return x.BuyRule
	}
	return ""
}

func (x *CreateVersionRequest) GetSellRule() string {
	if x != nil {
		return x.SellRule
	}
	return ""
}

func (x *CreateVersionRequest) GetRiskRule() string {
	if x != nil {
		return x.RiskRule
	}
	return ""
}

func (x *CreateVersionRequest) GetPositionRule() string {
	if x != nil {
		return x.PositionRule
	}
	return ""
}

func (x *CreateVersionRequest) GetRebalanceRule() string {
	if x != nil {
		return x.RebalanceRule
	}
	return ""
}

func (x *CreateVersionRequest) GetChangeLog() string {
	if x != nil {
		return x.ChangeLog
	}
	return ""
}

type CreateVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VersionId     int64                  `protobuf:"varint,1,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVersionResponse) Reset() {
	*x = CreateVersionResponse{}
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVersionResponse) ProtoMessage() {}

func (x *CreateVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVersionResponse.ProtoReflect.Descriptor instead.
func (*CreateVersionResponse) Descriptor() ([]byte, []int) {
	return file_api_strategy_v1_strategy_proto_rawDescGZIP(), []int{17}
}

func (x *CreateVersionResponse) GetVersionId() int64 {
	if x != nil {
		return x.VersionId
	}
	return 0
}

type ListVersionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrategyId    int64                  `protobuf:"varint,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVersionsRequest) Reset() {
	*x = ListVersionsRequest{}
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVersionsRequest) ProtoMessage() {}

func (x *ListVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVersionsRequest.ProtoReflect.Descriptor instead.
func (*ListVersionsRequest) Descriptor() ([]byte, []int) {
	return file_api_strategy_v1_strategy_proto_rawDescGZIP(), []int{18}
}

func (x *ListVersionsRequest) GetStrategyId() int64 {
	if x != nil {
		return x.StrategyId
	}
	return 0
}

type ListVersionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []*StrategyVersion     `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVersionsResponse) Reset() {
	*x = ListVersionsResponse{}
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVersionsResponse) ProtoMessage() {}

func (x *ListVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVersionsResponse.ProtoReflect.Descriptor instead.
func (*ListVersionsResponse) Descriptor() ([]byte, []int) {
	return file_api_strategy_v1_strategy_proto_rawDescGZIP(), []int{19}
}

func (x *ListVersionsResponse) GetVersions() []*StrategyVersion {
	if x != nil {
		return x.Versions
	}
	return nil
}

type GetVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VersionId     int64                  `protobuf:"varint,1,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionRequest) Reset() {
	*x = GetVersionRequest{}
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionRequest) ProtoMessage() {}

func (x *GetVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionRequest.ProtoReflect.Descriptor instead.
func (*GetVersionRequest) Descriptor() ([]byte, []int) {
	return file_api_strategy_v1_strategy_proto_rawDescGZIP(), []int{20}
}

func (x *GetVersionRequest) GetVersionId() int64 {
	if x != nil {
		return x.VersionId
	}
	return 0
}

type GetVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       *StrategyVersion       `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionResponse) Reset() {
	*x = GetVersionResponse{}
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionResponse) ProtoMessage() {}

func (x *GetVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionResponse.ProtoReflect.Descriptor instead.
func (*GetVersionResponse) Descriptor() ([]byte, []int) {
	return file_api_strategy_v1_strategy_proto_rawDescGZIP(), []int{21}
}

func (x *GetVersionResponse) GetVersion() *StrategyVersion {
	if x != nil {
		return x.Version
	}
	return nil
}

type SearchStrategiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Tags          []string               `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	AuthorId      int64                  `protobuf:"varint,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Sort          string                 `protobuf:"bytes,5,opt,name=sort,proto3" json:"sort,omitempty"`
	Cursor        *v1.Cursor             `protobuf:"bytes,6,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int32                  `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchStrategiesRequest) Reset() {
	*x = SearchStrategiesRequest{}
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchStrategiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchStrategiesRequest) ProtoMessage() {}

func (x *SearchStrategiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchStrategiesRequest.ProtoReflect.Descriptor instead.
func (*SearchStrategiesRequest) Descriptor() ([]byte, []int) {
	return file_api_strategy_v1_strategy_proto_rawDescGZIP(), []int{22}
}

func (x *SearchStrategiesRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchStrategiesRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SearchStrategiesRequest) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *SearchStrategiesRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *SearchStrategiesRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *SearchStrategiesRequest) GetCursor() *v1.Cursor {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *SearchStrategiesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchStrategiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Strategies    []*Strategy            `protobuf:"bytes,1,rep,name=strategies,proto3" json:"strategies,omitempty"`
	Cursor        *v1.Cursor             `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchStrategiesResponse) Reset() {
	*x = SearchStrategiesResponse{}
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchStrategiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchStrategiesResponse) ProtoMessage() {}

func (x *SearchStrategiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchStrategiesResponse.ProtoReflect.Descriptor instead.
func (*SearchStrategiesResponse) Descriptor() ([]byte, []int) {
	return file_api_strategy_v1_strategy_proto_rawDescGZIP(), []int{23}
}

func (x *SearchStrategiesResponse) GetStrategies() []*Strategy {
	if x != nil {
		return x.Strategies
	}
	return nil
}

func (x *SearchStrategiesResponse) GetCursor() *v1.Cursor {
	if x != nil {
		return x.Cursor
	}
	return nil
}

type ListStrategiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorId      int64                  `protobuf:"varint,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Status        v1.Status              `protobuf:"varint,2,opt,name=status,proto3,enum=common.Status" json:"status,omitempty"`
	Cursor        *v1.Cursor             `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStrategiesRequest) Reset() {
	*x = ListStrategiesRequest{}
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStrategiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStrategiesRequest) ProtoMessage() {}

func (x *ListStrategiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStrategiesRequest.ProtoReflect.Descriptor instead.
func (*ListStrategiesRequest) Descriptor() ([]byte, []int) {
	return file_api_strategy_v1_strategy_proto_rawDescGZIP(), []int{24}
}

func (x *ListStrategiesRequest) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *ListStrategiesRequest) GetStatus() v1.Status {
	if x != nil {
		return x.Status
	}
	return v1.Status(0)
}

func (x *ListStrategiesRequest) GetCursor() *v1.Cursor {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *ListStrategiesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListStrategiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Strategies    []*Strategy            `protobuf:"bytes,1,rep,name=strategies,proto3" json:"strategies,omitempty"`
	Cursor        *v1.Cursor             `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStrategiesResponse) Reset() {
	*x = ListStrategiesResponse{}
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStrategiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStrategiesResponse) ProtoMessage() {}

func (x *ListStrategiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_strategy_v1_strategy_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStrategiesResponse.ProtoReflect.Descriptor instead.
func (*ListStrategiesResponse) Descriptor() ([]byte, []int) {
	return file_api_strategy_v1_strategy_proto_rawDescGZIP(), []int{25}
}

func (x *ListStrategiesResponse) GetStrategies() []*Strategy {
	if x != nil {
		return x.Strategies
	}
	return nil
}

func (x *ListStrategiesResponse) GetCursor() *v1.Cursor {
	if x != nil {
		return x.Cursor
	}
	return nil
}

var File_api_strategy_v1_strategy_proto protoreflect.FileDescriptor

const file_api_strategy_v1_strategy_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/strategy/v1/strategy.proto\x12\bstrategy\x1a\x1aapi/common/v1/common.proto\"\xcc\x03\n" +
	"\bStrategy\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\x03R\bauthorId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12&\n" +
	"\x06status\x18\x05 \x01(\x0e2\x0e.common.StatusR\x06status\x122\n" +
	"\n" +
	"visibility\x18\x06 \x01(\x0e2\x12.common.VisibilityR\n" +
	"visibility\x12\x1a\n" +
	"\bcategory\x18\a \x01(\tR\bcategory\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x12,\n" +
	"\x12current_version_id\x18\t \x01(\x03R\x10currentVersionId\x12\x1d\n" +
	"\n" +
	"view_count\x18\n" +
	" \x01(\x03R\tviewCount\x12%\n" +
	"\x0efavorite_count\x18\v \x01(\x03R\rfavoriteCount\x12\x1d\n" +
	"\n" +
	"fork_count\x18\f \x01(\x03R\tforkCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\x03R\tupdatedAt\"\x82\x03\n" +
	"\x0fStrategyVersion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vstrategy_id\x18\x02 \x01(\x03R\n" +
	"strategyId\x12\x1d\n" +
	"\n" +
	"version_no\x18\x03 \x01(\tR\tversionNo\x12!\n" +
	"\fformula_text\x18\x04 \x01(\tR\vformulaText\x12\x19\n" +
	"\bbuy_rule\x18\x05 \x01(\tR\abuyRule\x12\x1b\n" +
	"\tsell_rule\x18\x06 \x01(\tR\bsellRule\x12\x1b\n" +
	"\trisk_rule\x18\a \x01(\tR\briskRule\x12#\n" +
	"\rposition_rule\x18\b \x01(\tR\fpositionRule\x12%\n" +
	"\x0erebalance_rule\x18\t \x01(\tR\rrebalanceRule\x12\x1d\n" +
	"\n" +
	"change_log\x18\n" +
	" \x01(\tR\tchangeLog\x12\x1d\n" +
	"\n" +
	"created_by\x18\v \x01(\x03R\tcreatedBy\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\x03R\tcreatedAt\"\x7f\n" +
	"\x15CreateStrategyRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\"9\n" +
	"\x16CreateStrategyResponse\x12\x1f\n" +
	"\vstrategy_id\x18\x01 \x01(\x03R\n" +
	"strategyId\"5\n" +
	"\x12GetStrategyRequest\x12\x1f\n" +
	"\vstrategy_id\x18\x01 \x01(\x03R\n" +
	"strategyId\"E\n" +
	"\x13GetStrategyResponse\x12.\n" +
	"\bstrategy\x18\x01 \x01(\v2\x12.strategy.StrategyR\bstrategy\"\xa0\x01\n" +
	"\x15UpdateStrategyRequest\x12\x1f\n" +
	"\vstrategy_id\x18\x01 \x01(\x03R\n" +
	"strategyId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\"\x18\n" +
	"\x16UpdateStrategyResponse\"8\n" +
	"\x15DeleteStrategyRequest\x12\x1f\n" +
	"\vstrategy_id\x18\x01 \x01(\x03R\n" +
	"strategyId\"\x18\n" +
	"\x16DeleteStrategyResponse\"X\n" +
	"\x16PublishStrategyRequest\x12\x1f\n" +
	"\vstrategy_id\x18\x01 \x01(\x03R\n" +
	"strategyId\x12\x1d\n" +
	"\n" +
	"version_id\x18\x02 \x01(\x03R\tversionId\"\x19\n" +
	"\x17PublishStrategyResponse\"9\n" +
	"\x16ArchiveStrategyRequest\x12\x1f\n" +
	"\vstrategy_id\x18\x01 \x01(\x03R\n" +
	"strategyId\"\x19\n" +
	"\x17ArchiveStrategyResponse\"C\n" +
	"\x13ForkStrategyRequest\x12,\n" +
	"\x12source_strategy_id\x18\x01 \x01(\x03R\x10sourceStrategyId\">\n" +
	"\x14ForkStrategyResponse\x12&\n" +
	"\x0fnew_strategy_id\x18\x01 \x01(\x03R\rnewStrategyId\"\x9a\x02\n" +
	"\x14CreateVersionRequest\x12\x1f\n" +
	"\vstrategy_id\x18\x01 \x01(\x03R\n" +
	"strategyId\x12!\n" +
	"\fformula_text\x18\x02 \x01(\tR\vformulaText\x12\x19\n" +
	"\bbuy_rule\x18\x03 \x01(\tR\abuyRule\x12\x1b\n" +
	"\tsell_rule\x18\x04 \x01(\tR\bsellRule\x12\x1b\n" +
	"\trisk_rule\x18\x05 \x01(\tR\briskRule\x12#\n" +
	"\rposition_rule\x18\x06 \x01(\tR\fpositionRule\x12%\n" +
	"\x0erebalance_rule\x18\a \x01(\tR\rrebalanceRule\x12\x1d\n" +
	"\n" +
	"change_log\x18\b \x01(\tR\tchangeLog\"6\n" +
	"\x15CreateVersionResponse\x12\x1d\n" +
	"\n" +
	"version_id\x18\x01 \x01(\x03R\tversionId\"6\n" +
	"\x13ListVersionsRequest\x12\x1f\n" +
	"\vstrategy_id\x18\x01 \x01(\x03R\n" +
	"strategyId\"M\n" +
	"\x14ListVersionsResponse\x125\n" +
	"\bversions\x18\x01 \x03(\v2\x19.strategy.StrategyVersionR\bversions\"2\n" +
	"\x11GetVersionRequest\x12\x1d\n" +
	"\n" +
	"version_id\x18\x01 \x01(\x03R\tversionId\"I\n" +
	"\x12GetVersionResponse\x123\n" +
	"\aversion\x18\x01 \x01(\v2\x19.strategy.StrategyVersionR\aversion\"\xd2\x01\n" +
	"\x17SearchStrategiesRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\x12\x1b\n" +
	"\tauthor_id\x18\x03 \x01(\x03R\bauthorId\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x12\n" +
	"\x04sort\x18\x05 \x01(\tR\x04sort\x12&\n" +
	"\x06cursor\x18\x06 \x01(\v2\x0e.common.CursorR\x06cursor\x12\x14\n" +
	"\x05limit\x18\a \x01(\x05R\x05limit\"v\n" +
	"\x18SearchStrategiesResponse\x122\n" +
	"\n" +
	"strategies\x18\x01 \x03(\v2\x12.strategy.StrategyR\n" +
	"strategies\x12&\n" +
	"\x06cursor\x18\x02 \x01(\v2\x0e.common.CursorR\x06cursor\"\x9a\x01\n" +
	"\x15ListStrategiesRequest\x12\x1b\n" +
	"\tauthor_id\x18\x01 \x01(\x03R\bauthorId\x12&\n" +
	"\x06status\x18\x02 \x01(\x0e2\x0e.common.StatusR\x06status\x12&\n" +
	"\x06cursor\x18\x03 \x01(\v2\x0e.common.CursorR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"t\n" +
	"\x16ListStrategiesResponse\x122\n" +
	"\n" +
	"strategies\x18\x01 \x03(\v2\x12.strategy.StrategyR\n" +
	"strategies\x12&\n" +
	"\x06cursor\x18\x02 \x01(\v2\x0e.common.CursorR\x06cursor2\xf5\a\n" +
	"\x0fStrategyService\x12S\n" +
	"\x0eCreateStrategy\x12\x1f.strategy.CreateStrategyRequest\x1a .strategy.CreateStrategyResponse\x12J\n" +
	"\vGetStrategy\x12\x1c.strategy.GetStrategyRequest\x1a\x1d.strategy.GetStrategyResponse\x12S\n" +
	"\x0eUpdateStrategy\x12\x1f.strategy.UpdateStrategyRequest\x1a .strategy.UpdateStrategyResponse\x12S\n" +
	"\x0eDeleteStrategy\x12\x1f.strategy.DeleteStrategyRequest\x1a .strategy.DeleteStrategyResponse\x12V\n" +
	"\x0fPublishStrategy\x12 .strategy.PublishStrategyRequest\x1a!.strategy.PublishStrategyResponse\x12V\n" +
	"\x0fArchiveStrategy\x12 .strategy.ArchiveStrategyRequest\x1a!.strategy.ArchiveStrategyResponse\x12M\n" +
	"\fForkStrategy\x12\x1d.strategy.ForkStrategyRequest\x1a\x1e.strategy.ForkStrategyResponse\x12P\n" +
	"\rCreateVersion\x12\x1e.strategy.CreateVersionRequest\x1a\x1f.strategy.CreateVersionResponse\x12M\n" +
	"\fListVersions\x12\x1d.strategy.ListVersionsRequest\x1a\x1e.strategy.ListVersionsResponse\x12G\n" +
	"\n" +
	"GetVersion\x12\x1b.strategy.GetVersionRequest\x1a\x1c.strategy.GetVersionResponse\x12Y\n" +
	"\x10SearchStrategies\x12!.strategy.SearchStrategiesRequest\x1a\".strategy.SearchStrategiesResponse\x12S\n" +
	"\x0eListStrategies\x12\x1f.strategy.ListStrategiesRequest\x1a .strategy.ListStrategiesResponseB+Z)github.com/agoXQ/QuantLab/app/strategy/pbb\x06proto3"

var (
	file_api_strategy_v1_strategy_proto_rawDescOnce sync.Once
	file_api_strategy_v1_strategy_proto_rawDescData []byte
)

func file_api_strategy_v1_strategy_proto_rawDescGZIP() []byte {
	file_api_strategy_v1_strategy_proto_rawDescOnce.Do(func() {
		file_api_strategy_v1_strategy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_strategy_v1_strategy_proto_rawDesc), len(file_api_strategy_v1_strategy_proto_rawDesc)))
	})
	return file_api_strategy_v1_strategy_proto_rawDescData
}

var file_api_strategy_v1_strategy_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_api_strategy_v1_strategy_proto_goTypes = []any{
	(*Strategy)(nil),                 // 0: strategy.Strategy
	(*StrategyVersion)(nil),          // 1: strategy.StrategyVersion
	(*CreateStrategyRequest)(nil),    // 2: strategy.CreateStrategyRequest
	(*CreateStrategyResponse)(nil),   // 3: strategy.CreateStrategyResponse
	(*GetStrategyRequest)(nil),       // 4: strategy.GetStrategyRequest
	(*GetStrategyResponse)(nil),      // 5: strategy.GetStrategyResponse
	(*UpdateStrategyRequest)(nil),    // 6: strategy.UpdateStrategyRequest
	(*UpdateStrategyResponse)(nil),   // 7: strategy.UpdateStrategyResponse
	(*DeleteStrategyRequest)(nil),    // 8: strategy.DeleteStrategyRequest
	(*DeleteStrategyResponse)(nil),   // 9: strategy.DeleteStrategyResponse
	(*PublishStrategyRequest)(nil),   // 10: strategy.PublishStrategyRequest
	(*PublishStrategyResponse)(nil),  // 11: strategy.PublishStrategyResponse
	(*ArchiveStrategyRequest)(nil),   // 12: strategy.ArchiveStrategyRequest
	(*ArchiveStrategyResponse)(nil),  // 13: strategy.ArchiveStrategyResponse
	(*ForkStrategyRequest)(nil),      // 14: strategy.ForkStrategyRequest
	(*ForkStrategyResponse)(nil),     // 15: strategy.ForkStrategyResponse
	(*CreateVersionRequest)(nil),     // 16: strategy.CreateVersionRequest
	(*CreateVersionResponse)(nil),    // 17: strategy.CreateVersionResponse
	(*ListVersionsRequest)(nil),      // 18: strategy.ListVersionsRequest
	(*ListVersionsResponse)(nil),     // 19: strategy.ListVersionsResponse
	(*GetVersionRequest)(nil),        // 20: strategy.GetVersionRequest
	(*GetVersionResponse)(nil),       // 21: strategy.GetVersionResponse
	(*SearchStrategiesRequest)(nil),  // 22: strategy.SearchStrategiesRequest
	(*SearchStrategiesResponse)(nil), // 23: strategy.SearchStrategiesResponse
	(*ListStrategiesRequest)(nil),    // 24: strategy.ListStrategiesRequest
	(*ListStrategiesResponse)(nil),   // 25: strategy.ListStrategiesResponse
	(v1.Status)(0),                   // 26: common.Status
	(v1.Visibility)(0),               // 27: common.Visibility
	(*v1.Cursor)(nil),                // 28: common.Cursor
}
var file_api_strategy_v1_strategy_proto_depIdxs = []int32{
	26, // 0: strategy.Strategy.status:type_name -> common.Status
	27, // 1: strategy.Strategy.visibility:type_name -> common.Visibility
	0,  // 2: strategy.GetStrategyResponse.strategy:type_name -> strategy.Strategy
	1,  // 3: strategy.ListVersionsResponse.versions:type_name -> strategy.StrategyVersion
	1,  // 4: strategy.GetVersionResponse.version:type_name -> strategy.StrategyVersion
	28, // 5: strategy.SearchStrategiesRequest.cursor:type_name -> common.Cursor
	0,  // 6: strategy.SearchStrategiesResponse.strategies:type_name -> strategy.Strategy
	28, // 7: strategy.SearchStrategiesResponse.cursor:type_name -> common.Cursor
	26, // 8: strategy.ListStrategiesRequest.status:type_name -> common.Status
	28, // 9: strategy.ListStrategiesRequest.cursor:type_name -> common.Cursor
	0,  // 10: strategy.ListStrategiesResponse.strategies:type_name -> strategy.Strategy
	28, // 11: strategy.ListStrategiesResponse.cursor:type_name -> common.Cursor
	2,  // 12: strategy.StrategyService.CreateStrategy:input_type -> strategy.CreateStrategyRequest
	4,  // 13: strategy.StrategyService.GetStrategy:input_type -> strategy.GetStrategyRequest
	6,  // 14: strategy.StrategyService.UpdateStrategy:input_type -> strategy.UpdateStrategyRequest
	8,  // 15: strategy.StrategyService.DeleteStrategy:input_type -> strategy.DeleteStrategyRequest
	10, // 16: strategy.StrategyService.PublishStrategy:input_type -> strategy.PublishStrategyRequest
	12, // 17: strategy.StrategyService.ArchiveStrategy:input_type -> strategy.ArchiveStrategyRequest
	14, // 18: strategy.StrategyService.ForkStrategy:input_type -> strategy.ForkStrategyRequest
	16, // 19: strategy.StrategyService.CreateVersion:input_type -> strategy.CreateVersionRequest
	18, // 20: strategy.StrategyService.ListVersions:input_type -> strategy.ListVersionsRequest
	20, // 21: strategy.StrategyService.GetVersion:input_type -> strategy.GetVersionRequest
	22, // 22: strategy.StrategyService.SearchStrategies:input_type -> strategy.SearchStrategiesRequest
	24, // 23: strategy.StrategyService.ListStrategies:input_type -> strategy.ListStrategiesRequest
	3,  // 24: strategy.StrategyService.CreateStrategy:output_type -> strategy.CreateStrategyResponse
	5,  // 25: strategy.StrategyService.GetStrategy:output_type -> strategy.GetStrategyResponse
	7,  // 26: strategy.StrategyService.UpdateStrategy:output_type -> strategy.UpdateStrategyResponse
	9,  // 27: strategy.StrategyService.DeleteStrategy:output_type -> strategy.DeleteStrategyResponse
	11, // 28: strategy.StrategyService.PublishStrategy:output_type -> strategy.PublishStrategyResponse
	13, // 29: strategy.StrategyService.ArchiveStrategy:output_type -> strategy.ArchiveStrategyResponse
	15, // 30: strategy.StrategyService.ForkStrategy:output_type -> strategy.ForkStrategyResponse
	17, // 31: strategy.StrategyService.CreateVersion:output_type -> strategy.CreateVersionResponse
	19, // 32: strategy.StrategyService.ListVersions:output_type -> strategy.ListVersionsResponse
	21, // 33: strategy.StrategyService.GetVersion:output_type -> strategy.GetVersionResponse
	23, // 34: strategy.StrategyService.SearchStrategies:output_type -> strategy.SearchStrategiesResponse
	25, // 35: strategy.StrategyService.ListStrategies:output_type -> strategy.ListStrategiesResponse
	24, // [24:36] is the sub-list for method output_type
	12, // [12:24] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_api_strategy_v1_strategy_proto_init() }
func file_api_strategy_v1_strategy_proto_init() {
	if File_api_strategy_v1_strategy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_strategy_v1_strategy_proto_rawDesc), len(file_api_strategy_v1_strategy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_strategy_v1_strategy_proto_goTypes,
		DependencyIndexes: file_api_strategy_v1_strategy_proto_depIdxs,
		MessageInfos:      file_api_strategy_v1_strategy_proto_msgTypes,
	}.Build()
	File_api_strategy_v1_strategy_proto = out.File
	file_api_strategy_v1_strategy_proto_goTypes = nil
	file_api_strategy_v1_strategy_proto_depIdxs = nil
}
