// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/ai/v1/ai.proto

package pb

import (
	_ "github.com/agoXQ/QuantLab/api/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskType int32

const (
	TaskType_TASK_TYPE_UNSPECIFIED TaskType = 0
	TaskType_GENERATE_STRATEGY     TaskType = 1
	TaskType_EXPLAIN_STRATEGY      TaskType = 2
	TaskType_OPTIMIZE_STRATEGY     TaskType = 3
	TaskType_GENERATE_PORTFOLIO    TaskType = 4
	TaskType_OPTIMIZE_PORTFOLIO    TaskType = 5
	TaskType_ANALYZE_BACKTEST      TaskType = 6
	TaskType_ASK_QUANTLAB          TaskType = 7
)

// Enum value maps for TaskType.
var (
	TaskType_name = map[int32]string{
		0: "TASK_TYPE_UNSPECIFIED",
		1: "GENERATE_STRATEGY",
		2: "EXPLAIN_STRATEGY",
		3: "OPTIMIZE_STRATEGY",
		4: "GENERATE_PORTFOLIO",
		5: "OPTIMIZE_PORTFOLIO",
		6: "ANALYZE_BACKTEST",
		7: "ASK_QUANTLAB",
	}
	TaskType_value = map[string]int32{
		"TASK_TYPE_UNSPECIFIED": 0,
		"GENERATE_STRATEGY":     1,
		"EXPLAIN_STRATEGY":      2,
		"OPTIMIZE_STRATEGY":     3,
		"GENERATE_PORTFOLIO":    4,
		"OPTIMIZE_PORTFOLIO":    5,
		"ANALYZE_BACKTEST":      6,
		"ASK_QUANTLAB":          7,
	}
)

func (x TaskType) Enum() *TaskType {
	p := new(TaskType)
	*p = x
	return p
}

func (x TaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_ai_v1_ai_proto_enumTypes[0].Descriptor()
}

func (TaskType) Type() protoreflect.EnumType {
	return &file_api_ai_v1_ai_proto_enumTypes[0]
}

func (x TaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskType.Descriptor instead.
func (TaskType) EnumDescriptor() ([]byte, []int) {
	return file_api_ai_v1_ai_proto_rawDescGZIP(), []int{0}
}

type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED TaskStatus = 0
	TaskStatus_PENDING                 TaskStatus = 1
	TaskStatus_RUNNING                 TaskStatus = 2
	TaskStatus_COMPLETED               TaskStatus = 3
	TaskStatus_FAILED                  TaskStatus = 4
	TaskStatus_CANCELLED               TaskStatus = 5
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "PENDING",
		2: "RUNNING",
		3: "COMPLETED",
		4: "FAILED",
		5: "CANCELLED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED": 0,
		"PENDING":                 1,
		"RUNNING":                 2,
		"COMPLETED":               3,
		"FAILED":                  4,
		"CANCELLED":               5,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_ai_v1_ai_proto_enumTypes[1].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_api_ai_v1_ai_proto_enumTypes[1]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_ai_v1_ai_proto_rawDescGZIP(), []int{1}
}

type AITask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TaskType      TaskType               `protobuf:"varint,3,opt,name=task_type,json=taskType,proto3,enum=ai.TaskType" json:"task_type,omitempty"`
	Status        TaskStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=ai.TaskStatus" json:"status,omitempty"`
	InputJson     string                 `protobuf:"bytes,5,opt,name=input_json,json=inputJson,proto3" json:"input_json,omitempty"`
	OutputJson    string                 `protobuf:"bytes,6,opt,name=output_json,json=outputJson,proto3" json:"output_json,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AITask) Reset() {
	*x = AITask{}
	mi := &file_api_ai_v1_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AITask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AITask) ProtoMessage() {}

func (x *AITask) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_v1_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AITask.ProtoReflect.Descriptor instead.
func (*AITask) Descriptor() ([]byte, []int) {
	return file_api_ai_v1_ai_proto_rawDescGZIP(), []int{0}
}

func (x *AITask) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AITask) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AITask) GetTaskType() TaskType {
	if x != nil {
		return x.TaskType
	}
	return TaskType_TASK_TYPE_UNSPECIFIED
}

func (x *AITask) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *AITask) GetInputJson() string {
	if x != nil {
		return x.InputJson
	}
	return ""
}

func (x *AITask) GetOutputJson() string {
	if x != nil {
		return x.OutputJson
	}
	return ""
}

func (x *AITask) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *AITask) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type AIReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ObjectType    string                 `protobuf:"bytes,2,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	ObjectId      int64                  `protobuf:"varint,3,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	Summary       string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	Strengths     string                 `protobuf:"bytes,5,opt,name=strengths,proto3" json:"strengths,omitempty"`
	Risks         string                 `protobuf:"bytes,6,opt,name=risks,proto3" json:"risks,omitempty"`
	Suggestions   string                 `protobuf:"bytes,7,opt,name=suggestions,proto3" json:"suggestions,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIReport) Reset() {
	*x = AIReport{}
	mi := &file_api_ai_v1_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIReport) ProtoMessage() {}

func (x *AIReport) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_v1_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIReport.ProtoReflect.Descriptor instead.
func (*AIReport) Descriptor() ([]byte, []int) {
	return file_api_ai_v1_ai_proto_rawDescGZIP(), []int{1}
}

func (x *AIReport) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AIReport) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *AIReport) GetObjectId() int64 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

func (x *AIReport) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *AIReport) GetStrengths() string {
	if x != nil {
		return x.Strengths
	}
	return ""
}

func (x *AIReport) GetRisks() string {
	if x != nil {
		return x.Risks
	}
	return ""
}

func (x *AIReport) GetSuggestions() string {
	if x != nil {
		return x.Suggestions
	}
	return ""
}

func (x *AIReport) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type GenerateStrategyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateStrategyRequest) Reset() {
	*x = GenerateStrategyRequest{}
	mi := &file_api_ai_v1_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateStrategyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateStrategyRequest) ProtoMessage() {}

func (x *GenerateStrategyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_v1_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateStrategyRequest.ProtoReflect.Descriptor instead.
func (*GenerateStrategyRequest) Descriptor() ([]byte, []int) {
	return file_api_ai_v1_ai_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateStrategyRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type GenerateStrategyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateStrategyResponse) Reset() {
	*x = GenerateStrategyResponse{}
	mi := &file_api_ai_v1_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateStrategyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateStrategyResponse) ProtoMessage() {}

func (x *GenerateStrategyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_v1_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateStrategyResponse.ProtoReflect.Descriptor instead.
func (*GenerateStrategyResponse) Descriptor() ([]byte, []int) {
	return file_api_ai_v1_ai_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateStrategyResponse) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type ExplainStrategyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrategyId    int64                  `protobuf:"varint,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplainStrategyRequest) Reset() {
	*x = ExplainStrategyRequest{}
	mi := &file_api_ai_v1_ai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainStrategyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainStrategyRequest) ProtoMessage() {}

func (x *ExplainStrategyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_v1_ai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainStrategyRequest.ProtoReflect.Descriptor instead.
func (*ExplainStrategyRequest) Descriptor() ([]byte, []int) {
	return file_api_ai_v1_ai_proto_rawDescGZIP(), []int{4}
}

func (x *ExplainStrategyRequest) GetStrategyId() int64 {
	if x != nil {
		return x.StrategyId
	}
	return 0
}

type ExplainStrategyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplainStrategyResponse) Reset() {
	*x = ExplainStrategyResponse{}
	mi := &file_api_ai_v1_ai_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainStrategyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainStrategyResponse) ProtoMessage() {}

func (x *ExplainStrategyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_v1_ai_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainStrategyResponse.ProtoReflect.Descriptor instead.
func (*ExplainStrategyResponse) Descriptor() ([]byte, []int) {
	return file_api_ai_v1_ai_proto_rawDescGZIP(), []int{5}
}

func (x *ExplainStrategyResponse) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type OptimizeStrategyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrategyId    int64                  `protobuf:"varint,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptimizeStrategyRequest) Reset() {
	*x = OptimizeStrategyRequest{}
	mi := &file_api_ai_v1_ai_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimizeStrategyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizeStrategyRequest) ProtoMessage() {}

func (x *OptimizeStrategyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_v1_ai_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizeStrategyRequest.ProtoReflect.Descriptor instead.
func (*OptimizeStrategyRequest) Descriptor() ([]byte, []int) {
	return file_api_ai_v1_ai_proto_rawDescGZIP(), []int{6}
}

func (x *OptimizeStrategyRequest) GetStrategyId() int64 {
	if x != nil {
		return x.StrategyId
	}
	return 0
}

type OptimizeStrategyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptimizeStrategyResponse) Reset() {
	*x = OptimizeStrategyResponse{}
	mi := &file_api_ai_v1_ai_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimizeStrategyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizeStrategyResponse) ProtoMessage() {}

func (x *OptimizeStrategyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_v1_ai_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizeStrategyResponse.ProtoReflect.Descriptor instead.
func (*OptimizeStrategyResponse) Descriptor() ([]byte, []int) {
	return file_api_ai_v1_ai_proto_rawDescGZIP(), []int{7}
}

func (x *OptimizeStrategyResponse) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type GeneratePortfolioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratePortfolioRequest) Reset() {
	*x = GeneratePortfolioRequest{}
	mi := &file_api_ai_v1_ai_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratePortfolioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratePortfolioRequest) ProtoMessage() {}

func (x *GeneratePortfolioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_v1_ai_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratePortfolioRequest.ProtoReflect.Descriptor instead.
func (*GeneratePortfolioRequest) Descriptor() ([]byte, []int) {
	return file_api_ai_v1_ai_proto_rawDescGZIP(), []int{8}
}

func (x *GeneratePortfolioRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type GeneratePortfolioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratePortfolioResponse) Reset() {
	*x = GeneratePortfolioResponse{}
	mi := &file_api_ai_v1_ai_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratePortfolioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratePortfolioResponse) ProtoMessage() {}

func (x *GeneratePortfolioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_v1_ai_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratePortfolioResponse.ProtoReflect.Descriptor instead.
func (*GeneratePortfolioResponse) Descriptor() ([]byte, []int) {
	return file_api_ai_v1_ai_proto_rawDescGZIP(), []int{9}
}

func (x *GeneratePortfolioResponse) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type OptimizePortfolioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PortfolioId   int64                  `protobuf:"varint,1,opt,name=portfolio_id,json=portfolioId,proto3" json:"portfolio_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptimizePortfolioRequest) Reset() {
	*x = OptimizePortfolioRequest{}
	mi := &file_api_ai_v1_ai_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimizePortfolioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizePortfolioRequest) ProtoMessage() {}

func (x *OptimizePortfolioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_v1_ai_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizePortfolioRequest.ProtoReflect.Descriptor instead.
func (*OptimizePortfolioRequest) Descriptor() ([]byte, []int) {
	return file_api_ai_v1_ai_proto_rawDescGZIP(), []int{10}
}

func (x *OptimizePortfolioRequest) GetPortfolioId() int64 {
	if x != nil {
		return x.PortfolioId
	}
	return 0
}

type OptimizePortfolioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptimizePortfolioResponse) Reset() {
	*x = OptimizePortfolioResponse{}
	mi := &file_api_ai_v1_ai_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimizePortfolioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizePortfolioResponse) ProtoMessage() {}

func (x *OptimizePortfolioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_v1_ai_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizePortfolioResponse.ProtoReflect.Descriptor instead.
func (*OptimizePortfolioResponse) Descriptor() ([]byte, []int) {
	return file_api_ai_v1_ai_proto_rawDescGZIP(), []int{11}
}

func (x *OptimizePortfolioResponse) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type AnalyzeBacktestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BacktestId    int64                  `protobuf:"varint,1,opt,name=backtest_id,json=backtestId,proto3" json:"backtest_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeBacktestRequest) Reset() {
	*x = AnalyzeBacktestRequest{}
	mi := &file_api_ai_v1_ai_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeBacktestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeBacktestRequest) ProtoMessage() {}

func (x *AnalyzeBacktestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_v1_ai_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeBacktestRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeBacktestRequest) Descriptor() ([]byte, []int) {
	return file_api_ai_v1_ai_proto_rawDescGZIP(), []int{12}
}

func (x *AnalyzeBacktestRequest) GetBacktestId() int64 {
	if x != nil {
		return x.BacktestId
	}
	return 0
}

type AnalyzeBacktestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeBacktestResponse) Reset() {
	*x = AnalyzeBacktestResponse{}
	mi := &file_api_ai_v1_ai_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeBacktestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeBacktestResponse) ProtoMessage() {}

func (x *AnalyzeBacktestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_v1_ai_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeBacktestResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeBacktestResponse) Descriptor() ([]byte, []int) {
	return file_api_ai_v1_ai_proto_rawDescGZIP(), []int{13}
}

func (x *AnalyzeBacktestResponse) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type ChatRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Message        string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	ConversationId int64                  `protobuf:"varint,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_api_ai_v1_ai_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_v1_ai_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_api_ai_v1_ai_proto_rawDescGZIP(), []int{14}
}

func (x *ChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatRequest) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

type ChatResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Reply          string                 `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	ConversationId int64                  `protobuf:"varint,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_api_ai_v1_ai_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_v1_ai_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_api_ai_v1_ai_proto_rawDescGZIP(), []int{15}
}

func (x *ChatResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

func (x *ChatResponse) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_api_ai_v1_ai_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_v1_ai_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_ai_v1_ai_proto_rawDescGZIP(), []int{16}
}

func (x *GetTaskRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *AITask                `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_api_ai_v1_ai_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_v1_ai_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_ai_v1_ai_proto_rawDescGZIP(), []int{17}
}

func (x *GetTaskResponse) GetTask() *AITask {
	if x != nil {
		return x.Task
	}
	return nil
}

type GetReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectType    string                 `protobuf:"bytes,1,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	ObjectId      int64                  `protobuf:"varint,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReportRequest) Reset() {
	*x = GetReportRequest{}
	mi := &file_api_ai_v1_ai_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReportRequest) ProtoMessage() {}

func (x *GetReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_v1_ai_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReportRequest.ProtoReflect.Descriptor instead.
func (*GetReportRequest) Descriptor() ([]byte, []int) {
	return file_api_ai_v1_ai_proto_rawDescGZIP(), []int{18}
}

func (x *GetReportRequest) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *GetReportRequest) GetObjectId() int64 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

type GetReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report        *AIReport              `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReportResponse) Reset() {
	*x = GetReportResponse{}
	mi := &file_api_ai_v1_ai_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReportResponse) ProtoMessage() {}

func (x *GetReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_v1_ai_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReportResponse.ProtoReflect.Descriptor instead.
func (*GetReportResponse) Descriptor() ([]byte, []int) {
	return file_api_ai_v1_ai_proto_rawDescGZIP(), []int{19}
}

func (x *GetReportResponse) GetReport() *AIReport {
	if x != nil {
		return x.Report
	}
	return nil
}

var File_api_ai_v1_ai_proto protoreflect.FileDescriptor

const file_api_ai_v1_ai_proto_rawDesc = "" +
	"\n" +
	"\x12api/ai/v1/ai.proto\x12\x02ai\x1a\x1aapi/common/v1/common.proto\"\x82\x02\n" +
	"\x06AITask\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12)\n" +
	"\ttask_type\x18\x03 \x01(\x0e2\f.ai.TaskTypeR\btaskType\x12&\n" +
	"\x06status\x18\x04 \x01(\x0e2\x0e.ai.TaskStatusR\x06status\x12\x1d\n" +
	"\n" +
	"input_json\x18\x05 \x01(\tR\tinputJson\x12\x1f\n" +
	"\voutput_json\x18\x06 \x01(\tR\n" +
	"outputJson\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\"\xe7\x01\n" +
	"\bAIReport\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vobject_type\x18\x02 \x01(\tR\n" +
	"objectType\x12\x1b\n" +
	"\tobject_id\x18\x03 \x01(\x03R\bobjectId\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12\x1c\n" +
	"\tstrengths\x18\x05 \x01(\tR\tstrengths\x12\x14\n" +
	"\x05risks\x18\x06 \x01(\tR\x05risks\x12 \n" +
	"\vsuggestions\x18\a \x01(\tR\vsuggestions\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\"1\n" +
	"\x17GenerateStrategyRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\"3\n" +
	"\x18GenerateStrategyResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\"9\n" +
	"\x16ExplainStrategyRequest\x12\x1f\n" +
	"\vstrategy_id\x18\x01 \x01(\x03R\n" +
	"strategyId\"2\n" +
	"\x17ExplainStrategyResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\":\n" +
	"\x17OptimizeStrategyRequest\x12\x1f\n" +
	"\vstrategy_id\x18\x01 \x01(\x03R\n" +
	"strategyId\"3\n" +
	"\x18OptimizeStrategyResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\"2\n" +
	"\x18GeneratePortfolioRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\"4\n" +
	"\x19GeneratePortfolioResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\"=\n" +
	"\x18OptimizePortfolioRequest\x12!\n" +
	"\fportfolio_id\x18\x01 \x01(\x03R\vportfolioId\"4\n" +
	"\x19OptimizePortfolioResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\"9\n" +
	"\x16AnalyzeBacktestRequest\x12\x1f\n" +
	"\vbacktest_id\x18\x01 \x01(\x03R\n" +
	"backtestId\"2\n" +
	"\x17AnalyzeBacktestResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\"P\n" +
	"\vChatRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\x03R\x0econversationId\"M\n" +
	"\fChatResponse\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\x03R\x0econversationId\")\n" +
	"\x0eGetTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\"1\n" +
	"\x0fGetTaskResponse\x12\x1e\n" +
	"\x04task\x18\x01 \x01(\v2\n" +
	".ai.AITaskR\x04task\"P\n" +
	"\x10GetReportRequest\x12\x1f\n" +
	"\vobject_type\x18\x01 \x01(\tR\n" +
	"objectType\x12\x1b\n" +
	"\tobject_id\x18\x02 \x01(\x03R\bobjectId\"9\n" +
	"\x11GetReportResponse\x12$\n" +
	"\x06report\x18\x01 \x01(\v2\f.ai.AIReportR\x06report*\xc1\x01\n" +
	"\bTaskType\x12\x19\n" +
	"\x15TASK_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11GENERATE_STRATEGY\x10\x01\x12\x14\n" +
	"\x10EXPLAIN_STRATEGY\x10\x02\x12\x15\n" +
	"\x11OPTIMIZE_STRATEGY\x10\x03\x12\x16\n" +
	"\x12GENERATE_PORTFOLIO\x10\x04\x12\x16\n" +
	"\x12OPTIMIZE_PORTFOLIO\x10\x05\x12\x14\n" +
	"\x10ANALYZE_BACKTEST\x10\x06\x12\x10\n" +
	"\fASK_QUANTLAB\x10\a*m\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\v\n" +
	"\aRUNNING\x10\x02\x12\r\n" +
	"\tCOMPLETED\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x04\x12\r\n" +
	"\tCANCELLED\x10\x052\xfe\x04\n" +
	"\tAIService\x12M\n" +
	"\x10GenerateStrategy\x12\x1b.ai.GenerateStrategyRequest\x1a\x1c.ai.GenerateStrategyResponse\x12J\n" +
	"\x0fExplainStrategy\x12\x1a.ai.ExplainStrategyRequest\x1a\x1b.ai.ExplainStrategyResponse\x12M\n" +
	"\x10OptimizeStrategy\x12\x1b.ai.OptimizeStrategyRequest\x1a\x1c.ai.OptimizeStrategyResponse\x12P\n" +
	"\x11GeneratePortfolio\x12\x1c.ai.GeneratePortfolioRequest\x1a\x1d.ai.GeneratePortfolioResponse\x12P\n" +
	"\x11OptimizePortfolio\x12\x1c.ai.OptimizePortfolioRequest\x1a\x1d.ai.OptimizePortfolioResponse\x12J\n" +
	"\x0fAnalyzeBacktest\x12\x1a.ai.AnalyzeBacktestRequest\x1a\x1b.ai.AnalyzeBacktestResponse\x12)\n" +
	"\x04Chat\x12\x0f.ai.ChatRequest\x1a\x10.ai.ChatResponse\x122\n" +
	"\aGetTask\x12\x12.ai.GetTaskRequest\x1a\x13.ai.GetTaskResponse\x128\n" +
	"\tGetReport\x12\x14.ai.GetReportRequest\x1a\x15.ai.GetReportResponseB%Z#github.com/agoXQ/QuantLab/app/ai/pbb\x06proto3"

var (
	file_api_ai_v1_ai_proto_rawDescOnce sync.Once
	file_api_ai_v1_ai_proto_rawDescData []byte
)

func file_api_ai_v1_ai_proto_rawDescGZIP() []byte {
	file_api_ai_v1_ai_proto_rawDescOnce.Do(func() {
		file_api_ai_v1_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_ai_v1_ai_proto_rawDesc), len(file_api_ai_v1_ai_proto_rawDesc)))
	})
	return file_api_ai_v1_ai_proto_rawDescData
}

var file_api_ai_v1_ai_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_ai_v1_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_api_ai_v1_ai_proto_goTypes = []any{
	(TaskType)(0),                     // 0: ai.TaskType
	(TaskStatus)(0),                   // 1: ai.TaskStatus
	(*AITask)(nil),                    // 2: ai.AITask
	(*AIReport)(nil),                  // 3: ai.AIReport
	(*GenerateStrategyRequest)(nil),   // 4: ai.GenerateStrategyRequest
	(*GenerateStrategyResponse)(nil),  // 5: ai.GenerateStrategyResponse
	(*ExplainStrategyRequest)(nil),    // 6: ai.ExplainStrategyRequest
	(*ExplainStrategyResponse)(nil),   // 7: ai.ExplainStrategyResponse
	(*OptimizeStrategyRequest)(nil),   // 8: ai.OptimizeStrategyRequest
	(*OptimizeStrategyResponse)(nil),  // 9: ai.OptimizeStrategyResponse
	(*GeneratePortfolioRequest)(nil),  // 10: ai.GeneratePortfolioRequest
	(*GeneratePortfolioResponse)(nil), // 11: ai.GeneratePortfolioResponse
	(*OptimizePortfolioRequest)(nil),  // 12: ai.OptimizePortfolioRequest
	(*OptimizePortfolioResponse)(nil), // 13: ai.OptimizePortfolioResponse
	(*AnalyzeBacktestRequest)(nil),    // 14: ai.AnalyzeBacktestRequest
	(*AnalyzeBacktestResponse)(nil),   // 15: ai.AnalyzeBacktestResponse
	(*ChatRequest)(nil),               // 16: ai.ChatRequest
	(*ChatResponse)(nil),              // 17: ai.ChatResponse
	(*GetTaskRequest)(nil),            // 18: ai.GetTaskRequest
	(*GetTaskResponse)(nil),           // 19: ai.GetTaskResponse
	(*GetReportRequest)(nil),          // 20: ai.GetReportRequest
	(*GetReportResponse)(nil),         // 21: ai.GetReportResponse
}
var file_api_ai_v1_ai_proto_depIdxs = []int32{
	0,  // 0: ai.AITask.task_type:type_name -> ai.TaskType
	1,  // 1: ai.AITask.status:type_name -> ai.TaskStatus
	2,  // 2: ai.GetTaskResponse.task:type_name -> ai.AITask
	3,  // 3: ai.GetReportResponse.report:type_name -> ai.AIReport
	4,  // 4: ai.AIService.GenerateStrategy:input_type -> ai.GenerateStrategyRequest
	6,  // 5: ai.AIService.ExplainStrategy:input_type -> ai.ExplainStrategyRequest
	8,  // 6: ai.AIService.OptimizeStrategy:input_type -> ai.OptimizeStrategyRequest
	10, // 7: ai.AIService.GeneratePortfolio:input_type -> ai.GeneratePortfolioRequest
	12, // 8: ai.AIService.OptimizePortfolio:input_type -> ai.OptimizePortfolioRequest
	14, // 9: ai.AIService.AnalyzeBacktest:input_type -> ai.AnalyzeBacktestRequest
	16, // 10: ai.AIService.Chat:input_type -> ai.ChatRequest
	18, // 11: ai.AIService.GetTask:input_type -> ai.GetTaskRequest
	20, // 12: ai.AIService.GetReport:input_type -> ai.GetReportRequest
	5,  // 13: ai.AIService.GenerateStrategy:output_type -> ai.GenerateStrategyResponse
	7,  // 14: ai.AIService.ExplainStrategy:output_type -> ai.ExplainStrategyResponse
	9,  // 15: ai.AIService.OptimizeStrategy:output_type -> ai.OptimizeStrategyResponse
	11, // 16: ai.AIService.GeneratePortfolio:output_type -> ai.GeneratePortfolioResponse
	13, // 17: ai.AIService.OptimizePortfolio:output_type -> ai.OptimizePortfolioResponse
	15, // 18: ai.AIService.AnalyzeBacktest:output_type -> ai.AnalyzeBacktestResponse
	17, // 19: ai.AIService.Chat:output_type -> ai.ChatResponse
	19, // 20: ai.AIService.GetTask:output_type -> ai.GetTaskResponse
	21, // 21: ai.AIService.GetReport:output_type -> ai.GetReportResponse
	13, // [13:22] is the sub-list for method output_type
	4,  // [4:13] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_ai_v1_ai_proto_init() }
func file_api_ai_v1_ai_proto_init() {
	if File_api_ai_v1_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_ai_v1_ai_proto_rawDesc), len(file_api_ai_v1_ai_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_ai_v1_ai_proto_goTypes,
		DependencyIndexes: file_api_ai_v1_ai_proto_depIdxs,
		EnumInfos:         file_api_ai_v1_ai_proto_enumTypes,
		MessageInfos:      file_api_ai_v1_ai_proto_msgTypes,
	}.Build()
	File_api_ai_v1_ai_proto = out.File
	file_api_ai_v1_ai_proto_goTypes = nil
	file_api_ai_v1_ai_proto_depIdxs = nil
}
