// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/billing/v1/billing.proto

package pb

import (
	v1 "github.com/agoXQ/QuantLab/api/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Membership struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MembershipId  string                 `protobuf:"bytes,1,opt,name=membership_id,json=membershipId,proto3" json:"membership_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Tier          string                 `protobuf:"bytes,3,opt,name=tier,proto3" json:"tier,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	AutoRenew     bool                   `protobuf:"varint,5,opt,name=auto_renew,json=autoRenew,proto3" json:"auto_renew,omitempty"`
	StartedAt     int64                  `protobuf:"varint,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	ExpiredAt     int64                  `protobuf:"varint,7,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Membership) Reset() {
	*x = Membership{}
	mi := &file_api_billing_v1_billing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Membership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Membership) ProtoMessage() {}

func (x *Membership) ProtoReflect() protoreflect.Message {
	mi := &file_api_billing_v1_billing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Membership.ProtoReflect.Descriptor instead.
func (*Membership) Descriptor() ([]byte, []int) {
	return file_api_billing_v1_billing_proto_rawDescGZIP(), []int{0}
}

func (x *Membership) GetMembershipId() string {
	if x != nil {
		return x.MembershipId
	}
	return ""
}

func (x *Membership) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Membership) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *Membership) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Membership) GetAutoRenew() bool {
	if x != nil {
		return x.AutoRenew
	}
	return false
}

func (x *Membership) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *Membership) GetExpiredAt() int64 {
	if x != nil {
		return x.ExpiredAt
	}
	return 0
}

type Subscription struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	SubscriberId   int64                  `protobuf:"varint,2,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"`
	ResourceType   string                 `protobuf:"bytes,3,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	ResourceId     string                 `protobuf:"bytes,4,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Status         string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	AutoRenew      bool                   `protobuf:"varint,6,opt,name=auto_renew,json=autoRenew,proto3" json:"auto_renew,omitempty"`
	StartedAt      int64                  `protobuf:"varint,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	ExpiredAt      int64                  `protobuf:"varint,8,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_api_billing_v1_billing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_api_billing_v1_billing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_api_billing_v1_billing_proto_rawDescGZIP(), []int{1}
}

func (x *Subscription) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *Subscription) GetSubscriberId() int64 {
	if x != nil {
		return x.SubscriberId
	}
	return 0
}

func (x *Subscription) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *Subscription) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *Subscription) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Subscription) GetAutoRenew() bool {
	if x != nil {
		return x.AutoRenew
	}
	return false
}

func (x *Subscription) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *Subscription) GetExpiredAt() int64 {
	if x != nil {
		return x.ExpiredAt
	}
	return 0
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderType     string                 `protobuf:"bytes,3,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	PaidAt        int64                  `protobuf:"varint,8,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_api_billing_v1_billing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_api_billing_v1_billing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_api_billing_v1_billing_proto_rawDescGZIP(), []int{2}
}

func (x *Order) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Order) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Order) GetOrderType() string {
	if x != nil {
		return x.OrderType
	}
	return ""
}

func (x *Order) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Order) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Order) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Order) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Order) GetPaidAt() int64 {
	if x != nil {
		return x.PaidAt
	}
	return 0
}

type Revenue struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RevenueShareId string                 `protobuf:"bytes,1,opt,name=revenue_share_id,json=revenueShareId,proto3" json:"revenue_share_id,omitempty"`
	OrderId        string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CreatorId      int64                  `protobuf:"varint,3,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	GrossAmount    float64                `protobuf:"fixed64,4,opt,name=gross_amount,json=grossAmount,proto3" json:"gross_amount,omitempty"`
	PlatformAmount float64                `protobuf:"fixed64,5,opt,name=platform_amount,json=platformAmount,proto3" json:"platform_amount,omitempty"`
	CreatorAmount  float64                `protobuf:"fixed64,6,opt,name=creator_amount,json=creatorAmount,proto3" json:"creator_amount,omitempty"`
	Status         string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Revenue) Reset() {
	*x = Revenue{}
	mi := &file_api_billing_v1_billing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Revenue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Revenue) ProtoMessage() {}

func (x *Revenue) ProtoReflect() protoreflect.Message {
	mi := &file_api_billing_v1_billing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Revenue.ProtoReflect.Descriptor instead.
func (*Revenue) Descriptor() ([]byte, []int) {
	return file_api_billing_v1_billing_proto_rawDescGZIP(), []int{3}
}

func (x *Revenue) GetRevenueShareId() string {
	if x != nil {
		return x.RevenueShareId
	}
	return ""
}

func (x *Revenue) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Revenue) GetCreatorId() int64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

func (x *Revenue) GetGrossAmount() float64 {
	if x != nil {
		return x.GrossAmount
	}
	return 0
}

func (x *Revenue) GetPlatformAmount() float64 {
	if x != nil {
		return x.PlatformAmount
	}
	return 0
}

func (x *Revenue) GetCreatorAmount() float64 {
	if x != nil {
		return x.CreatorAmount
	}
	return 0
}

func (x *Revenue) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Settlement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SettlementId  string                 `protobuf:"bytes,1,opt,name=settlement_id,json=settlementId,proto3" json:"settlement_id,omitempty"`
	CreatorId     int64                  `protobuf:"varint,2,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	RequestedAt   int64                  `protobuf:"varint,6,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	PaidAt        int64                  `protobuf:"varint,7,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Settlement) Reset() {
	*x = Settlement{}
	mi := &file_api_billing_v1_billing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Settlement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Settlement) ProtoMessage() {}

func (x *Settlement) ProtoReflect() protoreflect.Message {
	mi := &file_api_billing_v1_billing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Settlement.ProtoReflect.Descriptor instead.
func (*Settlement) Descriptor() ([]byte, []int) {
	return file_api_billing_v1_billing_proto_rawDescGZIP(), []int{4}
}

func (x *Settlement) GetSettlementId() string {
	if x != nil {
		return x.SettlementId
	}
	return ""
}

func (x *Settlement) GetCreatorId() int64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

func (x *Settlement) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Settlement) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Settlement) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Settlement) GetRequestedAt() int64 {
	if x != nil {
		return x.RequestedAt
	}
	return 0
}

func (x *Settlement) GetPaidAt() int64 {
	if x != nil {
		return x.PaidAt
	}
	return 0
}

type GetMembershipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMembershipRequest) Reset() {
	*x = GetMembershipRequest{}
	mi := &file_api_billing_v1_billing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMembershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembershipRequest) ProtoMessage() {}

func (x *GetMembershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_billing_v1_billing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembershipRequest.ProtoReflect.Descriptor instead.
func (*GetMembershipRequest) Descriptor() ([]byte, []int) {
	return file_api_billing_v1_billing_proto_rawDescGZIP(), []int{5}
}

func (x *GetMembershipRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetMembershipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Membership    *Membership            `protobuf:"bytes,1,opt,name=membership,proto3" json:"membership,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMembershipResponse) Reset() {
	*x = GetMembershipResponse{}
	mi := &file_api_billing_v1_billing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMembershipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembershipResponse) ProtoMessage() {}

func (x *GetMembershipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_billing_v1_billing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembershipResponse.ProtoReflect.Descriptor instead.
func (*GetMembershipResponse) Descriptor() ([]byte, []int) {
	return file_api_billing_v1_billing_proto_rawDescGZIP(), []int{6}
}

func (x *GetMembershipResponse) GetMembership() *Membership {
	if x != nil {
		return x.Membership
	}
	return nil
}

type PurchaseMembershipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tier          string                 `protobuf:"bytes,1,opt,name=tier,proto3" json:"tier,omitempty"`
	BillingCycle  string                 `protobuf:"bytes,2,opt,name=billing_cycle,json=billingCycle,proto3" json:"billing_cycle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseMembershipRequest) Reset() {
	*x = PurchaseMembershipRequest{}
	mi := &file_api_billing_v1_billing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseMembershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseMembershipRequest) ProtoMessage() {}

func (x *PurchaseMembershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_billing_v1_billing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseMembershipRequest.ProtoReflect.Descriptor instead.
func (*PurchaseMembershipRequest) Descriptor() ([]byte, []int) {
	return file_api_billing_v1_billing_proto_rawDescGZIP(), []int{7}
}

func (x *PurchaseMembershipRequest) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *PurchaseMembershipRequest) GetBillingCycle() string {
	if x != nil {
		return x.BillingCycle
	}
	return ""
}

type PurchaseMembershipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseMembershipResponse) Reset() {
	*x = PurchaseMembershipResponse{}
	mi := &file_api_billing_v1_billing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseMembershipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseMembershipResponse) ProtoMessage() {}

func (x *PurchaseMembershipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_billing_v1_billing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseMembershipResponse.ProtoReflect.Descriptor instead.
func (*PurchaseMembershipResponse) Descriptor() ([]byte, []int) {
	return file_api_billing_v1_billing_proto_rawDescGZIP(), []int{8}
}

func (x *PurchaseMembershipResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type CancelMembershipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelMembershipRequest) Reset() {
	*x = CancelMembershipRequest{}
	mi := &file_api_billing_v1_billing_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelMembershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelMembershipRequest) ProtoMessage() {}

func (x *CancelMembershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_billing_v1_billing_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelMembershipRequest.ProtoReflect.Descriptor instead.
func (*CancelMembershipRequest) Descriptor() ([]byte, []int) {
	return file_api_billing_v1_billing_proto_rawDescGZIP(), []int{9}
}

type CancelMembershipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelMembershipResponse) Reset() {
	*x = CancelMembershipResponse{}
	mi := &file_api_billing_v1_billing_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelMembershipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelMembershipResponse) ProtoMessage() {}

func (x *CancelMembershipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_billing_v1_billing_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelMembershipResponse.ProtoReflect.Descriptor instead.
func (*CancelMembershipResponse) Descriptor() ([]byte, []int) {
	return file_api_billing_v1_billing_proto_rawDescGZIP(), []int{10}
}

type CreateSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceType  string                 `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	ResourceId    string                 `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubscriptionRequest) Reset() {
	*x = CreateSubscriptionRequest{}
	mi := &file_api_billing_v1_billing_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionRequest) ProtoMessage() {}

func (x *CreateSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_billing_v1_billing_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_api_billing_v1_billing_proto_rawDescGZIP(), []int{11}
}

func (x *CreateSubscriptionRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type CreateSubscriptionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateSubscriptionResponse) Reset() {
	*x = CreateSubscriptionResponse{}
	mi := &file_api_billing_v1_billing_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionResponse) ProtoMessage() {}

func (x *CreateSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_billing_v1_billing_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_api_billing_v1_billing_proto_rawDescGZIP(), []int{12}
}

func (x *CreateSubscriptionResponse) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

type CancelSubscriptionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CancelSubscriptionRequest) Reset() {
	*x = CancelSubscriptionRequest{}
	mi := &file_api_billing_v1_billing_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSubscriptionRequest) ProtoMessage() {}

func (x *CancelSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_billing_v1_billing_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*CancelSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_api_billing_v1_billing_proto_rawDescGZIP(), []int{13}
}

func (x *CancelSubscriptionRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

type CancelSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelSubscriptionResponse) Reset() {
	*x = CancelSubscriptionResponse{}
	mi := &file_api_billing_v1_billing_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSubscriptionResponse) ProtoMessage() {}

func (x *CancelSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_billing_v1_billing_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*CancelSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_api_billing_v1_billing_proto_rawDescGZIP(), []int{14}
}

type ListSubscriptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Cursor        *v1.Cursor             `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubscriptionsRequest) Reset() {
	*x = ListSubscriptionsRequest{}
	mi := &file_api_billing_v1_billing_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubscriptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubscriptionsRequest) ProtoMessage() {}

func (x *ListSubscriptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_billing_v1_billing_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubscriptionsRequest.ProtoReflect.Descriptor instead.
func (*ListSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return file_api_billing_v1_billing_proto_rawDescGZIP(), []int{15}
}

func (x *ListSubscriptionsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListSubscriptionsRequest) GetCursor() *v1.Cursor {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *ListSubscriptionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListSubscriptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []*Subscription        `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	Cursor        *v1.Cursor             `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubscriptionsResponse) Reset() {
	*x = ListSubscriptionsResponse{}
	mi := &file_api_billing_v1_billing_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubscriptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubscriptionsResponse) ProtoMessage() {}

func (x *ListSubscriptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_billing_v1_billing_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubscriptionsResponse.ProtoReflect.Descriptor instead.
func (*ListSubscriptionsResponse) Descriptor() ([]byte, []int) {
	return file_api_billing_v1_billing_proto_rawDescGZIP(), []int{16}
}

func (x *ListSubscriptionsResponse) GetSubscriptions() []*Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

func (x *ListSubscriptionsResponse) GetCursor() *v1.Cursor {
	if x != nil {
		return x.Cursor
	}
	return nil
}

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderType     string                 `protobuf:"bytes,1,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"`
	ResourceId    string                 `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_api_billing_v1_billing_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_billing_v1_billing_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_billing_v1_billing_proto_rawDescGZIP(), []int{17}
}

func (x *CreateOrderRequest) GetOrderType() string {
	if x != nil {
		return x.OrderType
	}
	return ""
}

func (x *CreateOrderRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *CreateOrderRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateOrderRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_api_billing_v1_billing_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_billing_v1_billing_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_api_billing_v1_billing_proto_rawDescGZIP(), []int{18}
}

func (x *CreateOrderResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_api_billing_v1_billing_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_billing_v1_billing_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_billing_v1_billing_proto_rawDescGZIP(), []int{19}
}

func (x *GetOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type GetOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderResponse) Reset() {
	*x = GetOrderResponse{}
	mi := &file_api_billing_v1_billing_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse) ProtoMessage() {}

func (x *GetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_billing_v1_billing_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse.ProtoReflect.Descriptor instead.
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return file_api_billing_v1_billing_proto_rawDescGZIP(), []int{20}
}

func (x *GetOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type ListOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Cursor        *v1.Cursor             `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_api_billing_v1_billing_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest) ProtoMessage() {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_billing_v1_billing_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_api_billing_v1_billing_proto_rawDescGZIP(), []int{21}
}

func (x *ListOrdersRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListOrdersRequest) GetCursor() *v1.Cursor {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *ListOrdersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	Cursor        *v1.Cursor             `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersResponse) Reset() {
	*x = ListOrdersResponse{}
	mi := &file_api_billing_v1_billing_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersResponse) ProtoMessage() {}

func (x *ListOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_billing_v1_billing_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListOrdersResponse) Descriptor() ([]byte, []int) {
	return file_api_billing_v1_billing_proto_rawDescGZIP(), []int{22}
}

func (x *ListOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ListOrdersResponse) GetCursor() *v1.Cursor {
	if x != nil {
		return x.Cursor
	}
	return nil
}

type CreatePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Channel       string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentRequest) Reset() {
	*x = CreatePaymentRequest{}
	mi := &file_api_billing_v1_billing_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRequest) ProtoMessage() {}

func (x *CreatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_billing_v1_billing_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_api_billing_v1_billing_proto_rawDescGZIP(), []int{23}
}

func (x *CreatePaymentRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreatePaymentRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

type CreatePaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentUrl    string                 `protobuf:"bytes,1,opt,name=payment_url,json=paymentUrl,proto3" json:"payment_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentResponse) Reset() {
	*x = CreatePaymentResponse{}
	mi := &file_api_billing_v1_billing_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentResponse) ProtoMessage() {}

func (x *CreatePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_billing_v1_billing_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentResponse.ProtoReflect.Descriptor instead.
func (*CreatePaymentResponse) Descriptor() ([]byte, []int) {
	return file_api_billing_v1_billing_proto_rawDescGZIP(), []int{24}
}

func (x *CreatePaymentResponse) GetPaymentUrl() string {
	if x != nil {
		return x.PaymentUrl
	}
	return ""
}

type PaymentWebhookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       string                 `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	RawBody       []byte                 `protobuf:"bytes,2,opt,name=raw_body,json=rawBody,proto3" json:"raw_body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentWebhookRequest) Reset() {
	*x = PaymentWebhookRequest{}
	mi := &file_api_billing_v1_billing_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentWebhookRequest) ProtoMessage() {}

func (x *PaymentWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_billing_v1_billing_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentWebhookRequest.ProtoReflect.Descriptor instead.
func (*PaymentWebhookRequest) Descriptor() ([]byte, []int) {
	return file_api_billing_v1_billing_proto_rawDescGZIP(), []int{25}
}

func (x *PaymentWebhookRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *PaymentWebhookRequest) GetRawBody() []byte {
	if x != nil {
		return x.RawBody
	}
	return nil
}

type PaymentWebhookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentWebhookResponse) Reset() {
	*x = PaymentWebhookResponse{}
	mi := &file_api_billing_v1_billing_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentWebhookResponse) ProtoMessage() {}

func (x *PaymentWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_billing_v1_billing_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentWebhookResponse.ProtoReflect.Descriptor instead.
func (*PaymentWebhookResponse) Descriptor() ([]byte, []int) {
	return file_api_billing_v1_billing_proto_rawDescGZIP(), []int{26}
}

type GetCreatorRevenueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatorId     int64                  `protobuf:"varint,1,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCreatorRevenueRequest) Reset() {
	*x = GetCreatorRevenueRequest{}
	mi := &file_api_billing_v1_billing_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCreatorRevenueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCreatorRevenueRequest) ProtoMessage() {}

func (x *GetCreatorRevenueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_billing_v1_billing_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCreatorRevenueRequest.ProtoReflect.Descriptor instead.
func (*GetCreatorRevenueRequest) Descriptor() ([]byte, []int) {
	return file_api_billing_v1_billing_proto_rawDescGZIP(), []int{27}
}

func (x *GetCreatorRevenueRequest) GetCreatorId() int64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

type GetCreatorRevenueResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalRevenue   float64                `protobuf:"fixed64,1,opt,name=total_revenue,json=totalRevenue,proto3" json:"total_revenue,omitempty"`
	PendingRevenue float64                `protobuf:"fixed64,2,opt,name=pending_revenue,json=pendingRevenue,proto3" json:"pending_revenue,omitempty"`
	SettledRevenue float64                `protobuf:"fixed64,3,opt,name=settled_revenue,json=settledRevenue,proto3" json:"settled_revenue,omitempty"`
	RecentRevenues []*Revenue             `protobuf:"bytes,4,rep,name=recent_revenues,json=recentRevenues,proto3" json:"recent_revenues,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetCreatorRevenueResponse) Reset() {
	*x = GetCreatorRevenueResponse{}
	mi := &file_api_billing_v1_billing_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCreatorRevenueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCreatorRevenueResponse) ProtoMessage() {}

func (x *GetCreatorRevenueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_billing_v1_billing_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCreatorRevenueResponse.ProtoReflect.Descriptor instead.
func (*GetCreatorRevenueResponse) Descriptor() ([]byte, []int) {
	return file_api_billing_v1_billing_proto_rawDescGZIP(), []int{28}
}

func (x *GetCreatorRevenueResponse) GetTotalRevenue() float64 {
	if x != nil {
		return x.TotalRevenue
	}
	return 0
}

func (x *GetCreatorRevenueResponse) GetPendingRevenue() float64 {
	if x != nil {
		return x.PendingRevenue
	}
	return 0
}

func (x *GetCreatorRevenueResponse) GetSettledRevenue() float64 {
	if x != nil {
		return x.SettledRevenue
	}
	return 0
}

func (x *GetCreatorRevenueResponse) GetRecentRevenues() []*Revenue {
	if x != nil {
		return x.RecentRevenues
	}
	return nil
}

type RequestSettlementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        float64                `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestSettlementRequest) Reset() {
	*x = RequestSettlementRequest{}
	mi := &file_api_billing_v1_billing_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestSettlementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestSettlementRequest) ProtoMessage() {}

func (x *RequestSettlementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_billing_v1_billing_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestSettlementRequest.ProtoReflect.Descriptor instead.
func (*RequestSettlementRequest) Descriptor() ([]byte, []int) {
	return file_api_billing_v1_billing_proto_rawDescGZIP(), []int{29}
}

func (x *RequestSettlementRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RequestSettlementRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type RequestSettlementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SettlementId  string                 `protobuf:"bytes,1,opt,name=settlement_id,json=settlementId,proto3" json:"settlement_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestSettlementResponse) Reset() {
	*x = RequestSettlementResponse{}
	mi := &file_api_billing_v1_billing_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestSettlementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestSettlementResponse) ProtoMessage() {}

func (x *RequestSettlementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_billing_v1_billing_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestSettlementResponse.ProtoReflect.Descriptor instead.
func (*RequestSettlementResponse) Descriptor() ([]byte, []int) {
	return file_api_billing_v1_billing_proto_rawDescGZIP(), []int{30}
}

func (x *RequestSettlementResponse) GetSettlementId() string {
	if x != nil {
		return x.SettlementId
	}
	return ""
}

type ListSettlementsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatorId     int64                  `protobuf:"varint,1,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	Cursor        *v1.Cursor             `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSettlementsRequest) Reset() {
	*x = ListSettlementsRequest{}
	mi := &file_api_billing_v1_billing_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSettlementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSettlementsRequest) ProtoMessage() {}

func (x *ListSettlementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_billing_v1_billing_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSettlementsRequest.ProtoReflect.Descriptor instead.
func (*ListSettlementsRequest) Descriptor() ([]byte, []int) {
	return file_api_billing_v1_billing_proto_rawDescGZIP(), []int{31}
}

func (x *ListSettlementsRequest) GetCreatorId() int64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

func (x *ListSettlementsRequest) GetCursor() *v1.Cursor {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *ListSettlementsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListSettlementsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settlements   []*Settlement          `protobuf:"bytes,1,rep,name=settlements,proto3" json:"settlements,omitempty"`
	Cursor        *v1.Cursor             `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSettlementsResponse) Reset() {
	*x = ListSettlementsResponse{}
	mi := &file_api_billing_v1_billing_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSettlementsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSettlementsResponse) ProtoMessage() {}

func (x *ListSettlementsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_billing_v1_billing_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSettlementsResponse.ProtoReflect.Descriptor instead.
func (*ListSettlementsResponse) Descriptor() ([]byte, []int) {
	return file_api_billing_v1_billing_proto_rawDescGZIP(), []int{32}
}

func (x *ListSettlementsResponse) GetSettlements() []*Settlement {
	if x != nil {
		return x.Settlements
	}
	return nil
}

func (x *ListSettlementsResponse) GetCursor() *v1.Cursor {
	if x != nil {
		return x.Cursor
	}
	return nil
}

var File_api_billing_v1_billing_proto protoreflect.FileDescriptor

const file_api_billing_v1_billing_proto_rawDesc = "" +
	"\n" +
	"\x1capi/billing/v1/billing.proto\x12\abilling\x1a\x1aapi/common/v1/common.proto\"\xd3\x01\n" +
	"\n" +
	"Membership\x12#\n" +
	"\rmembership_id\x18\x01 \x01(\tR\fmembershipId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04tier\x18\x03 \x01(\tR\x04tier\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"auto_renew\x18\x05 \x01(\bR\tautoRenew\x12\x1d\n" +
	"\n" +
	"started_at\x18\x06 \x01(\x03R\tstartedAt\x12\x1d\n" +
	"\n" +
	"expired_at\x18\a \x01(\x03R\texpiredAt\"\x97\x02\n" +
	"\fSubscription\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12#\n" +
	"\rsubscriber_id\x18\x02 \x01(\x03R\fsubscriberId\x12#\n" +
	"\rresource_type\x18\x03 \x01(\tR\fresourceType\x12\x1f\n" +
	"\vresource_id\x18\x04 \x01(\tR\n" +
	"resourceId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"auto_renew\x18\x06 \x01(\bR\tautoRenew\x12\x1d\n" +
	"\n" +
	"started_at\x18\a \x01(\x03R\tstartedAt\x12\x1d\n" +
	"\n" +
	"expired_at\x18\b \x01(\x03R\texpiredAt\"\xde\x01\n" +
	"\x05Order\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"order_type\x18\x03 \x01(\tR\torderType\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x17\n" +
	"\apaid_at\x18\b \x01(\x03R\x06paidAt\"\xf8\x01\n" +
	"\aRevenue\x12(\n" +
	"\x10revenue_share_id\x18\x01 \x01(\tR\x0erevenueShareId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x03 \x01(\x03R\tcreatorId\x12!\n" +
	"\fgross_amount\x18\x04 \x01(\x01R\vgrossAmount\x12'\n" +
	"\x0fplatform_amount\x18\x05 \x01(\x01R\x0eplatformAmount\x12%\n" +
	"\x0ecreator_amount\x18\x06 \x01(\x01R\rcreatorAmount\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\"\xd8\x01\n" +
	"\n" +
	"Settlement\x12#\n" +
	"\rsettlement_id\x18\x01 \x01(\tR\fsettlementId\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x02 \x01(\x03R\tcreatorId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12!\n" +
	"\frequested_at\x18\x06 \x01(\x03R\vrequestedAt\x12\x17\n" +
	"\apaid_at\x18\a \x01(\x03R\x06paidAt\"/\n" +
	"\x14GetMembershipRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"L\n" +
	"\x15GetMembershipResponse\x123\n" +
	"\n" +
	"membership\x18\x01 \x01(\v2\x13.billing.MembershipR\n" +
	"membership\"T\n" +
	"\x19PurchaseMembershipRequest\x12\x12\n" +
	"\x04tier\x18\x01 \x01(\tR\x04tier\x12#\n" +
	"\rbilling_cycle\x18\x02 \x01(\tR\fbillingCycle\"7\n" +
	"\x1aPurchaseMembershipResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"\x19\n" +
	"\x17CancelMembershipRequest\"\x1a\n" +
	"\x18CancelMembershipResponse\"a\n" +
	"\x19CreateSubscriptionRequest\x12#\n" +
	"\rresource_type\x18\x01 \x01(\tR\fresourceType\x12\x1f\n" +
	"\vresource_id\x18\x02 \x01(\tR\n" +
	"resourceId\"E\n" +
	"\x1aCreateSubscriptionResponse\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\"D\n" +
	"\x19CancelSubscriptionRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\"\x1c\n" +
	"\x1aCancelSubscriptionResponse\"q\n" +
	"\x18ListSubscriptionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12&\n" +
	"\x06cursor\x18\x02 \x01(\v2\x0e.common.CursorR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\x80\x01\n" +
	"\x19ListSubscriptionsResponse\x12;\n" +
	"\rsubscriptions\x18\x01 \x03(\v2\x15.billing.SubscriptionR\rsubscriptions\x12&\n" +
	"\x06cursor\x18\x02 \x01(\v2\x0e.common.CursorR\x06cursor\"\x88\x01\n" +
	"\x12CreateOrderRequest\x12\x1d\n" +
	"\n" +
	"order_type\x18\x01 \x01(\tR\torderType\x12\x1f\n" +
	"\vresource_id\x18\x02 \x01(\tR\n" +
	"resourceId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\"0\n" +
	"\x13CreateOrderResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\",\n" +
	"\x0fGetOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"8\n" +
	"\x10GetOrderResponse\x12$\n" +
	"\x05order\x18\x01 \x01(\v2\x0e.billing.OrderR\x05order\"j\n" +
	"\x11ListOrdersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12&\n" +
	"\x06cursor\x18\x02 \x01(\v2\x0e.common.CursorR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"d\n" +
	"\x12ListOrdersResponse\x12&\n" +
	"\x06orders\x18\x01 \x03(\v2\x0e.billing.OrderR\x06orders\x12&\n" +
	"\x06cursor\x18\x02 \x01(\v2\x0e.common.CursorR\x06cursor\"K\n" +
	"\x14CreatePaymentRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\"8\n" +
	"\x15CreatePaymentResponse\x12\x1f\n" +
	"\vpayment_url\x18\x01 \x01(\tR\n" +
	"paymentUrl\"L\n" +
	"\x15PaymentWebhookRequest\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12\x19\n" +
	"\braw_body\x18\x02 \x01(\fR\arawBody\"\x18\n" +
	"\x16PaymentWebhookResponse\"9\n" +
	"\x18GetCreatorRevenueRequest\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x01 \x01(\x03R\tcreatorId\"\xcd\x01\n" +
	"\x19GetCreatorRevenueResponse\x12#\n" +
	"\rtotal_revenue\x18\x01 \x01(\x01R\ftotalRevenue\x12'\n" +
	"\x0fpending_revenue\x18\x02 \x01(\x01R\x0ependingRevenue\x12'\n" +
	"\x0fsettled_revenue\x18\x03 \x01(\x01R\x0esettledRevenue\x129\n" +
	"\x0frecent_revenues\x18\x04 \x03(\v2\x10.billing.RevenueR\x0erecentRevenues\"N\n" +
	"\x18RequestSettlementRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"@\n" +
	"\x19RequestSettlementResponse\x12#\n" +
	"\rsettlement_id\x18\x01 \x01(\tR\fsettlementId\"u\n" +
	"\x16ListSettlementsRequest\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x01 \x01(\x03R\tcreatorId\x12&\n" +
	"\x06cursor\x18\x02 \x01(\v2\x0e.common.CursorR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"x\n" +
	"\x17ListSettlementsResponse\x125\n" +
	"\vsettlements\x18\x01 \x03(\v2\x13.billing.SettlementR\vsettlements\x12&\n" +
	"\x06cursor\x18\x02 \x01(\v2\x0e.common.CursorR\x06cursor2\xb5\t\n" +
	"\x0eBillingService\x12N\n" +
	"\rGetMembership\x12\x1d.billing.GetMembershipRequest\x1a\x1e.billing.GetMembershipResponse\x12]\n" +
	"\x12PurchaseMembership\x12\".billing.PurchaseMembershipRequest\x1a#.billing.PurchaseMembershipResponse\x12W\n" +
	"\x10CancelMembership\x12 .billing.CancelMembershipRequest\x1a!.billing.CancelMembershipResponse\x12]\n" +
	"\x12CreateSubscription\x12\".billing.CreateSubscriptionRequest\x1a#.billing.CreateSubscriptionResponse\x12]\n" +
	"\x12CancelSubscription\x12\".billing.CancelSubscriptionRequest\x1a#.billing.CancelSubscriptionResponse\x12Z\n" +
	"\x11ListSubscriptions\x12!.billing.ListSubscriptionsRequest\x1a\".billing.ListSubscriptionsResponse\x12H\n" +
	"\vCreateOrder\x12\x1b.billing.CreateOrderRequest\x1a\x1c.billing.CreateOrderResponse\x12?\n" +
	"\bGetOrder\x12\x18.billing.GetOrderRequest\x1a\x19.billing.GetOrderResponse\x12E\n" +
	"\n" +
	"ListOrders\x12\x1a.billing.ListOrdersRequest\x1a\x1b.billing.ListOrdersResponse\x12N\n" +
	"\rCreatePayment\x12\x1d.billing.CreatePaymentRequest\x1a\x1e.billing.CreatePaymentResponse\x12Q\n" +
	"\x0ePaymentWebhook\x12\x1e.billing.PaymentWebhookRequest\x1a\x1f.billing.PaymentWebhookResponse\x12Z\n" +
	"\x11GetCreatorRevenue\x12!.billing.GetCreatorRevenueRequest\x1a\".billing.GetCreatorRevenueResponse\x12Z\n" +
	"\x11RequestSettlement\x12!.billing.RequestSettlementRequest\x1a\".billing.RequestSettlementResponse\x12T\n" +
	"\x0fListSettlements\x12\x1f.billing.ListSettlementsRequest\x1a .billing.ListSettlementsResponseB*Z(github.com/agoXQ/QuantLab/app/billing/pbb\x06proto3"

var (
	file_api_billing_v1_billing_proto_rawDescOnce sync.Once
	file_api_billing_v1_billing_proto_rawDescData []byte
)

func file_api_billing_v1_billing_proto_rawDescGZIP() []byte {
	file_api_billing_v1_billing_proto_rawDescOnce.Do(func() {
		file_api_billing_v1_billing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_billing_v1_billing_proto_rawDesc), len(file_api_billing_v1_billing_proto_rawDesc)))
	})
	return file_api_billing_v1_billing_proto_rawDescData
}

var file_api_billing_v1_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_api_billing_v1_billing_proto_goTypes = []any{
	(*Membership)(nil),                 // 0: billing.Membership
	(*Subscription)(nil),               // 1: billing.Subscription
	(*Order)(nil),                      // 2: billing.Order
	(*Revenue)(nil),                    // 3: billing.Revenue
	(*Settlement)(nil),                 // 4: billing.Settlement
	(*GetMembershipRequest)(nil),       // 5: billing.GetMembershipRequest
	(*GetMembershipResponse)(nil),      // 6: billing.GetMembershipResponse
	(*PurchaseMembershipRequest)(nil),  // 7: billing.PurchaseMembershipRequest
	(*PurchaseMembershipResponse)(nil), // 8: billing.PurchaseMembershipResponse
	(*CancelMembershipRequest)(nil),    // 9: billing.CancelMembershipRequest
	(*CancelMembershipResponse)(nil),   // 10: billing.CancelMembershipResponse
	(*CreateSubscriptionRequest)(nil),  // 11: billing.CreateSubscriptionRequest
	(*CreateSubscriptionResponse)(nil), // 12: billing.CreateSubscriptionResponse
	(*CancelSubscriptionRequest)(nil),  // 13: billing.CancelSubscriptionRequest
	(*CancelSubscriptionResponse)(nil), // 14: billing.CancelSubscriptionResponse
	(*ListSubscriptionsRequest)(nil),   // 15: billing.ListSubscriptionsRequest
	(*ListSubscriptionsResponse)(nil),  // 16: billing.ListSubscriptionsResponse
	(*CreateOrderRequest)(nil),         // 17: billing.CreateOrderRequest
	(*CreateOrderResponse)(nil),        // 18: billing.CreateOrderResponse
	(*GetOrderRequest)(nil),            // 19: billing.GetOrderRequest
	(*GetOrderResponse)(nil),           // 20: billing.GetOrderResponse
	(*ListOrdersRequest)(nil),          // 21: billing.ListOrdersRequest
	(*ListOrdersResponse)(nil),         // 22: billing.ListOrdersResponse
	(*CreatePaymentRequest)(nil),       // 23: billing.CreatePaymentRequest
	(*CreatePaymentResponse)(nil),      // 24: billing.CreatePaymentResponse
	(*PaymentWebhookRequest)(nil),      // 25: billing.PaymentWebhookRequest
	(*PaymentWebhookResponse)(nil),     // 26: billing.PaymentWebhookResponse
	(*GetCreatorRevenueRequest)(nil),   // 27: billing.GetCreatorRevenueRequest
	(*GetCreatorRevenueResponse)(nil),  // 28: billing.GetCreatorRevenueResponse
	(*RequestSettlementRequest)(nil),   // 29: billing.RequestSettlementRequest
	(*RequestSettlementResponse)(nil),  // 30: billing.RequestSettlementResponse
	(*ListSettlementsRequest)(nil),     // 31: billing.ListSettlementsRequest
	(*ListSettlementsResponse)(nil),    // 32: billing.ListSettlementsResponse
	(*v1.Cursor)(nil),                  // 33: common.Cursor
}
var file_api_billing_v1_billing_proto_depIdxs = []int32{
	0,  // 0: billing.GetMembershipResponse.membership:type_name -> billing.Membership
	33, // 1: billing.ListSubscriptionsRequest.cursor:type_name -> common.Cursor
	1,  // 2: billing.ListSubscriptionsResponse.subscriptions:type_name -> billing.Subscription
	33, // 3: billing.ListSubscriptionsResponse.cursor:type_name -> common.Cursor
	2,  // 4: billing.GetOrderResponse.order:type_name -> billing.Order
	33, // 5: billing.ListOrdersRequest.cursor:type_name -> common.Cursor
	2,  // 6: billing.ListOrdersResponse.orders:type_name -> billing.Order
	33, // 7: billing.ListOrdersResponse.cursor:type_name -> common.Cursor
	3,  // 8: billing.GetCreatorRevenueResponse.recent_revenues:type_name -> billing.Revenue
	33, // 9: billing.ListSettlementsRequest.cursor:type_name -> common.Cursor
	4,  // 10: billing.ListSettlementsResponse.settlements:type_name -> billing.Settlement
	33, // 11: billing.ListSettlementsResponse.cursor:type_name -> common.Cursor
	5,  // 12: billing.BillingService.GetMembership:input_type -> billing.GetMembershipRequest
	7,  // 13: billing.BillingService.PurchaseMembership:input_type -> billing.PurchaseMembershipRequest
	9,  // 14: billing.BillingService.CancelMembership:input_type -> billing.CancelMembershipRequest
	11, // 15: billing.BillingService.CreateSubscription:input_type -> billing.CreateSubscriptionRequest
	13, // 16: billing.BillingService.CancelSubscription:input_type -> billing.CancelSubscriptionRequest
	15, // 17: billing.BillingService.ListSubscriptions:input_type -> billing.ListSubscriptionsRequest
	17, // 18: billing.BillingService.CreateOrder:input_type -> billing.CreateOrderRequest
	19, // 19: billing.BillingService.GetOrder:input_type -> billing.GetOrderRequest
	21, // 20: billing.BillingService.ListOrders:input_type -> billing.ListOrdersRequest
	23, // 21: billing.BillingService.CreatePayment:input_type -> billing.CreatePaymentRequest
	25, // 22: billing.BillingService.PaymentWebhook:input_type -> billing.PaymentWebhookRequest
	27, // 23: billing.BillingService.GetCreatorRevenue:input_type -> billing.GetCreatorRevenueRequest
	29, // 24: billing.BillingService.RequestSettlement:input_type -> billing.RequestSettlementRequest
	31, // 25: billing.BillingService.ListSettlements:input_type -> billing.ListSettlementsRequest
	6,  // 26: billing.BillingService.GetMembership:output_type -> billing.GetMembershipResponse
	8,  // 27: billing.BillingService.PurchaseMembership:output_type -> billing.PurchaseMembershipResponse
	10, // 28: billing.BillingService.CancelMembership:output_type -> billing.CancelMembershipResponse
	12, // 29: billing.BillingService.CreateSubscription:output_type -> billing.CreateSubscriptionResponse
	14, // 30: billing.BillingService.CancelSubscription:output_type -> billing.CancelSubscriptionResponse
	16, // 31: billing.BillingService.ListSubscriptions:output_type -> billing.ListSubscriptionsResponse
	18, // 32: billing.BillingService.CreateOrder:output_type -> billing.CreateOrderResponse
	20, // 33: billing.BillingService.GetOrder:output_type -> billing.GetOrderResponse
	22, // 34: billing.BillingService.ListOrders:output_type -> billing.ListOrdersResponse
	24, // 35: billing.BillingService.CreatePayment:output_type -> billing.CreatePaymentResponse
	26, // 36: billing.BillingService.PaymentWebhook:output_type -> billing.PaymentWebhookResponse
	28, // 37: billing.BillingService.GetCreatorRevenue:output_type -> billing.GetCreatorRevenueResponse
	30, // 38: billing.BillingService.RequestSettlement:output_type -> billing.RequestSettlementResponse
	32, // 39: billing.BillingService.ListSettlements:output_type -> billing.ListSettlementsResponse
	26, // [26:40] is the sub-list for method output_type
	12, // [12:26] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_api_billing_v1_billing_proto_init() }
func file_api_billing_v1_billing_proto_init() {
	if File_api_billing_v1_billing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_billing_v1_billing_proto_rawDesc), len(file_api_billing_v1_billing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_billing_v1_billing_proto_goTypes,
		DependencyIndexes: file_api_billing_v1_billing_proto_depIdxs,
		MessageInfos:      file_api_billing_v1_billing_proto_msgTypes,
	}.Build()
	File_api_billing_v1_billing_proto = out.File
	file_api_billing_v1_billing_proto_goTypes = nil
	file_api_billing_v1_billing_proto_depIdxs = nil
}
