// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: market.proto

package server

import (
	"context"

	"github.com/agoXQ/QuantLab/app/market/internal/logic"
	"github.com/agoXQ/QuantLab/app/market/internal/svc"
	"github.com/agoXQ/QuantLab/app/market/pb"
)

type MarketDataServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedMarketDataServiceServer
}

func NewMarketDataServiceServer(svcCtx *svc.ServiceContext) *MarketDataServiceServer {
	return &MarketDataServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *MarketDataServiceServer) GetSecurity(ctx context.Context, in *pb.GetSecurityRequest) (*pb.GetSecurityResponse, error) {
	l := logic.NewGetSecurityLogic(ctx, s.svcCtx)
	return l.GetSecurity(in)
}

func (s *MarketDataServiceServer) ListSecurities(ctx context.Context, in *pb.ListSecuritiesRequest) (*pb.ListSecuritiesResponse, error) {
	l := logic.NewListSecuritiesLogic(ctx, s.svcCtx)
	return l.ListSecurities(in)
}

func (s *MarketDataServiceServer) GetBars(ctx context.Context, in *pb.GetBarsRequest) (*pb.GetBarsResponse, error) {
	l := logic.NewGetBarsLogic(ctx, s.svcCtx)
	return l.GetBars(in)
}

func (s *MarketDataServiceServer) GetFinancials(ctx context.Context, in *pb.GetFinancialsRequest) (*pb.GetFinancialsResponse, error) {
	l := logic.NewGetFinancialsLogic(ctx, s.svcCtx)
	return l.GetFinancials(in)
}

func (s *MarketDataServiceServer) GetFactors(ctx context.Context, in *pb.GetFactorsRequest) (*pb.GetFactorsResponse, error) {
	l := logic.NewGetFactorsLogic(ctx, s.svcCtx)
	return l.GetFactors(in)
}

func (s *MarketDataServiceServer) GetIndex(ctx context.Context, in *pb.GetIndexRequest) (*pb.GetIndexResponse, error) {
	l := logic.NewGetIndexLogic(ctx, s.svcCtx)
	return l.GetIndex(in)
}

func (s *MarketDataServiceServer) GetCalendar(ctx context.Context, in *pb.GetCalendarRequest) (*pb.GetCalendarResponse, error) {
	l := logic.NewGetCalendarLogic(ctx, s.svcCtx)
	return l.GetCalendar(in)
}

func (s *MarketDataServiceServer) GetVersions(ctx context.Context, in *pb.GetVersionsRequest) (*pb.GetVersionsResponse, error) {
	l := logic.NewGetVersionsLogic(ctx, s.svcCtx)
	return l.GetVersions(in)
}
