// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: market.proto

package marketdataservice

import (
	"context"

	"github.com/agoXQ/QuantLab/app/market/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DataVersion            = pb.DataVersion
	FactorData             = pb.FactorData
	FinancialStatement     = pb.FinancialStatement
	GetBarsRequest         = pb.GetBarsRequest
	GetBarsResponse        = pb.GetBarsResponse
	GetCalendarRequest     = pb.GetCalendarRequest
	GetCalendarResponse    = pb.GetCalendarResponse
	GetFactorsRequest      = pb.GetFactorsRequest
	GetFactorsResponse     = pb.GetFactorsResponse
	GetFinancialsRequest   = pb.GetFinancialsRequest
	GetFinancialsResponse  = pb.GetFinancialsResponse
	GetIndexRequest        = pb.GetIndexRequest
	GetIndexResponse       = pb.GetIndexResponse
	GetSecurityRequest     = pb.GetSecurityRequest
	GetSecurityResponse    = pb.GetSecurityResponse
	GetVersionsRequest     = pb.GetVersionsRequest
	GetVersionsResponse    = pb.GetVersionsResponse
	IndexBar               = pb.IndexBar
	ListSecuritiesRequest  = pb.ListSecuritiesRequest
	ListSecuritiesResponse = pb.ListSecuritiesResponse
	MarketBar              = pb.MarketBar
	Security               = pb.Security
	TradingCalendar        = pb.TradingCalendar

	MarketDataService interface {
		GetSecurity(ctx context.Context, in *GetSecurityRequest, opts ...grpc.CallOption) (*GetSecurityResponse, error)
		ListSecurities(ctx context.Context, in *ListSecuritiesRequest, opts ...grpc.CallOption) (*ListSecuritiesResponse, error)
		GetBars(ctx context.Context, in *GetBarsRequest, opts ...grpc.CallOption) (*GetBarsResponse, error)
		GetFinancials(ctx context.Context, in *GetFinancialsRequest, opts ...grpc.CallOption) (*GetFinancialsResponse, error)
		GetFactors(ctx context.Context, in *GetFactorsRequest, opts ...grpc.CallOption) (*GetFactorsResponse, error)
		GetIndex(ctx context.Context, in *GetIndexRequest, opts ...grpc.CallOption) (*GetIndexResponse, error)
		GetCalendar(ctx context.Context, in *GetCalendarRequest, opts ...grpc.CallOption) (*GetCalendarResponse, error)
		GetVersions(ctx context.Context, in *GetVersionsRequest, opts ...grpc.CallOption) (*GetVersionsResponse, error)
	}

	defaultMarketDataService struct {
		cli zrpc.Client
	}
)

func NewMarketDataService(cli zrpc.Client) MarketDataService {
	return &defaultMarketDataService{
		cli: cli,
	}
}

func (m *defaultMarketDataService) GetSecurity(ctx context.Context, in *GetSecurityRequest, opts ...grpc.CallOption) (*GetSecurityResponse, error) {
	client := pb.NewMarketDataServiceClient(m.cli.Conn())
	return client.GetSecurity(ctx, in, opts...)
}

func (m *defaultMarketDataService) ListSecurities(ctx context.Context, in *ListSecuritiesRequest, opts ...grpc.CallOption) (*ListSecuritiesResponse, error) {
	client := pb.NewMarketDataServiceClient(m.cli.Conn())
	return client.ListSecurities(ctx, in, opts...)
}

func (m *defaultMarketDataService) GetBars(ctx context.Context, in *GetBarsRequest, opts ...grpc.CallOption) (*GetBarsResponse, error) {
	client := pb.NewMarketDataServiceClient(m.cli.Conn())
	return client.GetBars(ctx, in, opts...)
}

func (m *defaultMarketDataService) GetFinancials(ctx context.Context, in *GetFinancialsRequest, opts ...grpc.CallOption) (*GetFinancialsResponse, error) {
	client := pb.NewMarketDataServiceClient(m.cli.Conn())
	return client.GetFinancials(ctx, in, opts...)
}

func (m *defaultMarketDataService) GetFactors(ctx context.Context, in *GetFactorsRequest, opts ...grpc.CallOption) (*GetFactorsResponse, error) {
	client := pb.NewMarketDataServiceClient(m.cli.Conn())
	return client.GetFactors(ctx, in, opts...)
}

func (m *defaultMarketDataService) GetIndex(ctx context.Context, in *GetIndexRequest, opts ...grpc.CallOption) (*GetIndexResponse, error) {
	client := pb.NewMarketDataServiceClient(m.cli.Conn())
	return client.GetIndex(ctx, in, opts...)
}

func (m *defaultMarketDataService) GetCalendar(ctx context.Context, in *GetCalendarRequest, opts ...grpc.CallOption) (*GetCalendarResponse, error) {
	client := pb.NewMarketDataServiceClient(m.cli.Conn())
	return client.GetCalendar(ctx, in, opts...)
}

func (m *defaultMarketDataService) GetVersions(ctx context.Context, in *GetVersionsRequest, opts ...grpc.CallOption) (*GetVersionsResponse, error) {
	client := pb.NewMarketDataServiceClient(m.cli.Conn())
	return client.GetVersions(ctx, in, opts...)
}
